### ISSUE TITLE
non-free components

### ISSUE THREAD

**Issue by IzzySoft** [CappielloAntonio/tempo#1]
First thanks for providing this app under a FOSS license! It has some non-free (proprietary) components, though, which I'm not sure if they're really needed for the app's functionality. Maybe they could be removed/replaced?

```
Offending libs:
---------------
* Firebase Data Transport (/com/google/android/datatransport): NonFreeNet
* Google Cast (/com/google/android/gms/cast): NonFreeDep
* Google Mobile Services (/com/google/android/gms): NonFreeDep
* Firebase (/com/google/firebase): NonFreeNet,NonFreeDep

4 offenders.
```

My guess is your intention was just to add support for Google Cast, which then dragged in the other 3 – so they cannot be easily removed without losing that functionality. But a possibility could e.g. be to have a "FOSS build flavor" without Cast then, and make that APK also available? Thanks in advance!

**Comment by IzzySoft** [comment]
PS: there's a little versioning problem. The APK at tag 3.3.2 identifies as 3.3.0, not sure if that was intended:

    package: name='com.cappielloantonio.tempo' versionCode='5' versionName='3.3.0'

**Comment by CappielloAntonio** [comment]
Yes, you are absolutely right. The cast feature needs the following implementation: 'com.google.android.gms:play-services-cast-framework:xx.xx.xx'.

I already intended to create a flavor without cast and Android Auto functionality that I could publish on third-party stores, I'll try to work on it in the near future.

And yes, my bad! I created a tag without updating the 'versionName'

**Comment by IzzySoft** [comment]
Thanks for taking care! Please keep me updated when you found time to work on it (no pressure of course!) – and if you have questions, feel free to ask.

For some background: I've [added your app](https://apt.izzysoft.de/fdroid/index/apk/com.cappielloantonio.tempo) to my repo to make it easier to find, install and update especially for those outside Google's walled gardens. My updater was currently set to check monthly (as otherwise it would pull the same APK over and again, expecting to find the 3.3.2 :see_no_evil: I've just switched it to daily checks as versioning is fixed now (update will show up with the next sync around 6 pm UTC). Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link there e.g. from your Readme :smiley:

**Comment by IzzySoft** [comment]
PS:

> I already intended to create a flavor without cast and Android Auto functionality that I could publish on third-party stores, I'll try to work on it in the near future.

That would then probably be eligible for listing at [F-Droid.org](https://f-droid.org/) even. Let's see when the flavor is ready, I might be able to help you with a listing there then if you wish (disclosure: I'm one of the maintainers there).

**Comment by CappielloAntonio** [comment]
Here I am with some updates. As I promised myself, I created the new flavor by eliminating the non-free components, i.e. all those features that revolved around the cast.

It took me longer than expected because combining the two flavors means removing the file that creates the split from the main branch and adding it in each branch. There would have been no problem except that the parts affected by this duplication would have been more than I had anticipated, but above all I would have had to duplicate important classes and in the long run it would have been a nightmare.

All this to say that I've done a fairly major refactor of the affected code, so these changes are currently only available to the dev branch, for the time to test the two apps carefully.

Hopefully, I'll bring everything back to master in the next few days and release a new version of the app.

**Comment by IzzySoft** [comment]
Thanks for the heads-up! When all is ready, will you attach both APKs to `releases/` – and if so, what naming schema will you use? Shall I then stick with the "full build" and you want to bring the FOSS-one to F-Droid.org? And if so, once it's listed there, shall I keep the "other one" in my repo to give people a choice? One more thing to consider is if both variants shall share the same `applicationId` of if you'd better have them use different ones to avoid confusion :wink:

**Comment by CappielloAntonio** [comment]
Hi @IzzySoft, It's been a while!
Today I followed the app submission procedure on F-Droid, I hope I didn't screw up.

Right now there are two builds, one with applicationId `com.cappielloantonio.tempo` and the other `com.cappielloantonio.notquitemy.tempo`.

I'd like to continue publishing the complete build here on GitHub, while on F-Droid I'd like to publish the app without the non-free components. You can choose whether to keep only the new version on your store or whether to keep the old version as well.

I apologize for the time elapsed between one message and another, more and more commitments and changes to be made have added up which have pushed the publication on F-Droid into the background.

**Comment by IzzySoft** [comment]
What naming schemes will the APKs at `releases/` use so I know which to pick? I'd suggest dropping the one also published at F-Droid.org from my repo approx. 10..14d after it became available there, and then stick to the other one (which won't be available there). As the one to keep is the more complete anyway, there might not be a reason to establish the other one with my repo to start with, what do you think?

**Comment by CappielloAntonio** [comment]
The apk published in /releases will follows the classic `app-tempo-release.apk` (if I were to decide to publish the apk intended for F-Droid as well it would be called `app-notquitemytempo-release.apk`). No tag included.

Hope I answered your question.

And yes, I agree with keeping the full version of the app.

**Comment by IzzySoft** [comment]
OK, so I've just pinned the app in my repo to APKs matching `/app-tempo-release/i` – and to definitely ignore `/notquitemytempo/i` which is intended for F-Droid.org. All prepared on my end then, thanks!

**Comment by CappielloAntonio** [comment]
Thanks to you! I hope I don't have any problems with F-Droid. 
In case I have problems in the future, I may reopen this issue.

**Comment by IzzySoft** [comment]
Sure. And you'll probably meet me over at F-Droid as well (disclosure: I'm one of the maintainers there) :wink:

**Comment by hubortje** [comment]
Hey, I cannot find Tempo on F-Droid, did you stop publishing it there?

**Comment by IzzySoft** [comment]
@hubortje it's currently [in my repo](https://apt.izzysoft.de/packages/com.cappielloantonio.tempo/) which you can add to your client. Looks like @CappielloAntonio did not yet manage to get rid of the proprietary components (unless that was done with a separate build flavor for `com.cappielloantonio.notquitemy.tempo`), which would mean F-Droid cannot yet include it.

**Comment by hubortje** [comment]
Thank you, @IzzySoft!
Then shouldn't this issue be reopened?

**Comment by IzzySoft** [comment]
This issue here was about "non-free components". I don't know if it is solved with a separate build flavor (there is no second APK at the releases I could check), so I have to leave this question to @CappielloAntonio.
