### ISSUE TITLE
[Feature Request] - More aggresive caching during playback

### ISSUE THREAD

**Issue by SinTan1729** [CappielloAntonio/tempo#102]
## Summary
The caching of songs should be more aggresive during playback.

## Description
Add an option to cache the whole song currently being played, or even better, cache the current song and the next song.

## Use Case
I'm not sure exactly how long, but currently, Tempo caches around 30 seconds of the song at a time. This is usually fine. But if I'm traveling, on a bus, or walking around in University, I have patchy connection as I connect and disconnect from WiFi. So the playback stops intermittently. If the caching were better, this won't happen.

## Additional context
Substreamer has a similar option, which does solve this problem somewhat.

**Comment by CappielloAntonio** [comment]
I implemented this function by setting a minimum buffering time ranging from a few seconds to over five minutes, beyond which I don't think it's necessary.

The multipliers used are Minimum (.1), Moderate (1), Aggressive (4), Extreme (8) which must be multiplied by the default time of the music player which is 50 seconds.

The new version is now online.
