### ISSUE TITLE
[Feature Request] - Disable scrobbler

### ISSUE THREAD

**Issue by Cambi0nn** [CappielloAntonio/tempo#104]
## Summary
Allow Last.FM scrobbling trough Tempo to be disabled.

## Description
Allow Last.FM scrobbling trough Tempo to be disabled. The front page says it's optional but there doesn't seem to be any setting to disable scrobbling.

## Use Case
In some cases people might want to use secondary apps to scrobble music, like Pano Scrobbler. For example to be able to access features regarding scrobbling not in the music app and use the extra settings of a dedicated app to finetune scrobbling behaviour, or simply to scrobble easily from multiple apps from one place. Currently it's not possible to disable scrobbling trough Tempo, which results in double scrobblers if another app is used.

## Additional context
Most other SubSonic players do have a setting to disable scrobbling, so I would think it's possible on a technical side.

**Comment by CappielloAntonio** [comment]
Feature implemented. 
It will be released soon together with the new version of Tempo.
