### ISSUE TITLE
[Feature Request] - Landscape orientation 

### ISSUE THREAD

**Issue by ra1qcw** [CappielloAntonio/tempo#110]
Awesome player! Thank you! 

But it hard to use in the car, some element in the player cover each other. Add landscape orientation please!
![IMG_20231128_135613.jpg](https://github.com/CappielloAntonio/tempo/assets/14166496/9a085409-f3c7-4380-94a3-f18ef106de37)

**Comment by CappielloAntonio** [comment]
Hi @ra1qcw, the landscape music player is coming in the next release!

![Screenshot_20231212-213003_Tempo](https://github.com/CappielloAntonio/tempo/assets/14802539/b914d691-b769-415d-8772-590cf1fefd9a)

**Comment by ra1qcw** [comment]
> Hi @ra1qcw, the landscape music player is coming in the next release!
> 
> ![Screenshot_20231212-213003_Tempo](https://github.com/CappielloAntonio/tempo/assets/14802539/b914d691-b769-415d-8772-590cf1fefd9a)
> 

Awesome! Thank You!
It will be best player ever!
