### ISSUE TITLE
[Feature Request] - Ignore tracks with a 1-star rating

### ISSUE THREAD

**Issue by michael-ball** [CappielloAntonio/tempo#111]
## Summary
I'd like tracks with a 1-star rating to not be added to the play queue when using "Shuffle all" or playing an artist radio.

## Description
I've previously been using DSub before switching to Tempo, and DSub had some really useful behaviour where it would exclude any tracks with a 1-star rating from being added to the play queue.

## Use Case
This is useful for preventing tracks such as "silence" tracks (often found at the end of CD albums to create a lengthy silence before 1 or more hidden tracks) from being added to the play queue when using the "Shuffle all" or artist radio features.

**Comment by CappielloAntonio** [comment]
Hi, great request!
I have implemented it and will be part of the next release.
