### ISSUE TITLE
[BUG] - Album art appears in notification player, but not in main player

### ISSUE THREAD

**Issue by molohov** [CappielloAntonio/tempo#113]
## Describe the bug
Album art appears in the notification player, but not in the main player or the search results 

## Expected behavior
Album art should appear everywhere

## To Reproduce
Play a song, observe the notification player vs the main player

## Environment
 - Android device: Pixel 6 Pro
 - Android OS version: 13
 - App version: 3.5.8
 - Other relevant details: **Gonic v0.16.1** 

## Logs or Screenshots
[Screen recording of the issue
](https://youtube.com/shorts/RoWpqlFn5I8)

**Comment by molohov** [comment]
I resolved the issue of the album art not appearing in the main player by learning that Gonic does not fetch embedded album art. Adding album art into the music folder and then rescanning the library allows Tempo to see the album art. 

However, I find it interesting that the notification player worked at all in the past. Was it fetching the embedded art somehow?

**Comment by CappielloAntonio** [comment]
Hello @molohov, does the file you're playing have the artwork embedded? Media3, the library I'm using, could be using that if the artwork uri is missing.

**Comment by molohov** [comment]
Correct, the art is embedded. Why doesn't it work in the main player though?

**Comment by CappielloAntonio** [comment]
Because everywhere, except for the notification, I manually create a mediaItem inside which, in addition to the various metadata, there is also the uri for the artwork (if it is present in the response given to me by the server). Evidently the notification makes do as best it can in case the mediaItem being played does not have the defined artwork, taking it from the stream.

**Comment by molohov** [comment]
I understand. So is there any possible fix?

**Comment by CappielloAntonio** [comment]
I don't think it's something that needs fixing. One option could be to not make the image visible in notifications neither when the server doesn't return the coverArt field, but I think in this unexpected situation it's not totally a bad thing.
