### ISSUE TITLE
[CRASH] - Tempo will not start

### ISSUE THREAD

**Issue by c0utta** [CappielloAntonio/tempo#117]
## Description
Tempo will not start, after configuring and downloading music.  These _seems_ to happen when there is a large amount of downloaded music.

## Steps to Reproduce
I can't!  I have restarted my device, but Tempo refuses to start.  Have to uninstall and install again.

## Environment
 - Android device: Pixel Pro 8
 - Android OS version: 14
 - App version: 3.5.8
 - Other relevant details: None

## Crash Logs/Stack trace
No unsigned apk for this release.  Not sure where to get the logs even with the apk

## Screenshots
Not applicable

## Additional Context
Not applicable

## Reproducibility
Always happens after the first time the crash occurs

## Additional Notes
Not applicable

**Comment by CappielloAntonio** [comment]
Hi @c0utta, could you send me the crash log with this version of the app signed with the debug key?

[app-tempo-debug.zip](https://github.com/CappielloAntonio/tempo/files/13653081/app-tempo-debug.zip)
