### ISSUE TITLE
[BUG] - Hiding podcasts actually hides radio

### ISSUE THREAD

**Issue by phw** [CappielloAntonio/tempo#123]
## Describe the bug

By default the UI shows tabs for Music, Podcasts, and Radio. I have no podcasts butusic and radios on the server. So the podcast list shows a message that there are no podcasts, but the radiologist is filled.

When disabling podcasts in the UI the tabs show correctly only "Music" and "Radio", but tapping on radio shows the empty podcast list with the message there are no podcasts.

## Expected behavior

The radio list is shown

## To Reproduce

1. Disable podcasts in settings
2. Click on 'Radio'

## Environment
 - Android OS version: 12
 - App version: 3.5.8
 
## Logs or Screenshots

![Screenshot_20231224-095503](https://github.com/CappielloAntonio/tempo/assets/29852/bab4b9a0-7770-4885-af76-517747ec421b)

**Comment by CappielloAntonio** [comment]
Hi @phw,
For the setting to take full effect you need to recreate the fragment, and the simplest way to do this is to restart the app. I made sure to make the settings message more clear.
