### ISSUE TITLE
[BUG] - Update 3.6.0 Broke LineageOS black mode

### ISSUE THREAD

**Issue by OhaDerErste** [CappielloAntonio/tempo#126]
## Describe the bug
LineageOS has a option to make the background of apps completely black instead of the material you gray. 

## Expected behavior
Background should be black, like in 3.5.8

## To Reproduce
1. Enable Pure black in LineageOS settings
2. Open the app

## Environment
 - Android device: Google Pixel 5
 - Android OS version: LineageOS 20
 - App version: 3.6.0

## Logs or Screenshots
3.5.8  
![Screenshot_20240103-153540_Tempo](https://github.com/CappielloAntonio/tempo/assets/77100649/c8060cb4-a7c1-4a02-94f6-b3b5af67f4b3)
3.6.0  
![Screenshot_20240103-153151_Tempo](https://github.com/CappielloAntonio/tempo/assets/77100649/09d212e0-f504-4208-866a-a3386549ca64)

**Comment by OPerepadia** [comment]
I have a similar issue after the recent update to 3.6.0. In my case, some UI elements are almost invisible.
Here are screenshots for the dark theme, but it affects the light theme in the same way.
3.5.8 on the left, 3.6.0 on the right
![out](https://github.com/CappielloAntonio/tempo/assets/80095612/1d3beaf9-2a9b-42c8-b928-bb8669e4224b)

**Comment by CappielloAntonio** [comment]
Thanks for the tip! 
The problem occurred after [updating](https://github.com/CappielloAntonio/tempo/commit/e8c7c065e21da2a987730d6071ec47fd63c6d3b5) the com.google.android.material library from 1.10.0 to 1.11.0. It would be a minor release if [they hadn't changed an important piece of logic](https://github.com/material-components/material-components-android/releases/tag/1.11.0).

For those interested, [here is the full article on the Google blog](https://material.io/blog/tone-based-surface-color-m3).

I didn't realize it at first, but there is a problem. 
The question is whether I can correct it now without "upsetting" anything.

**Comment by OhaDerErste** [comment]
Issue seems to be fixed with 3.7, thanks!
