### ISSUE TITLE
How do I get the subsonic servers. Give me instructions. How to get the subsonic servers/API.

### ISSUE THREAD

**Issue by OmarNazzal150** [CappielloAntonio/tempo#130]

**Comment by PatrickDelancy** [comment]
You will typically need to install some Subsonic compatible server software, and provide your own music files.

Here are a few of popular options:
* [Official Subsonic API](http://www.subsonic.org/pages/download.jsp)
* [Gonic](https://github.com/sentriz/gonic)
* [Navidrome](https://github.com/navidrome/navidrome)
* [LMS](https://github.com/epoupon/lms)
* [Ampache](https://github.com/ampache/ampache)

**Comment by daedric7** [comment]
I've tried Gonic, Navidrome, Airsonic-NG.

Which is the advisable one?

**Comment by OmarNazzal150** [comment]
How can I do all of this on mobile. Not desktop

**Comment by kaibagley** [comment]
Correct me if I'm wrong, but if you're only interested in doing everything on mobile then you're better off using a regular music player app to play the audio files you'll have saved on your phone, rather than Tempo which is designed to be used with a remote Subsonic server
