### ISSUE TITLE
[Feature Request] - Add option to display song file type & bitrate

### ISSUE THREAD

**Issue by vestyc** [CappielloAntonio/tempo#131]
## Summary
Add an option in the settings to display file type and bitrate of all songs.

## Description
When the 'display bitrate' and/or 'display file type' option is enabled, the extra details of the song should be visible with the other details such as artist name and total song time.

## Use Case
Navidrome servers (specifically) allow for duplicate albums and songs. Bitrate is one factor that allows a user to tell 2 duplicates apart and can help the user organize their library.

## Additional context
Here's a mock up for a single song from an album view:
![1000000563-edited](https://github.com/CappielloAntonio/tempo/assets/11786430/4b68f80b-5b72-437d-80df-61f34657ce87)

The [Ultrasonic ](https://gitlab.com/ultrasonic/ultrasonic) android app has this feature implemented and looks like this:
(Currently playing view):
![1000000564-edited](https://github.com/CappielloAntonio/tempo/assets/11786430/76a6de01-ea6a-4dc3-81bb-653571b5a835)
(Album view):
![1000000565](https://github.com/CappielloAntonio/tempo/assets/11786430/17fbc04f-9cdd-4023-9bfa-ccb7d15ea777)

**Comment by CappielloAntonio** [comment]
I don't particularly like the idea of having other information as the subtitle of the audio element, but I implemented it by making visibility optional. The next time release will contain this new option.

![Screenshot_20240218-170422_Tempo](https://github.com/CappielloAntonio/tempo/assets/14802539/a776e399-3cfb-4cbd-b224-fb2d04b4239f)

**Comment by vestyc** [comment]
Great news! Thank you for taking the time to add this minor feature. I'll definitely make the switch now.
