### ISSUE TITLE
[Feature Request] - Launch app in "offine" mode

### ISSUE THREAD

**Issue by ScrambleTheRamble** [CappielloAntonio/tempo#132]
## Summary
I would love the ability to launch the application in "offline" mode

## Description
My current Navidrome setup is not accessible from outside my lan so I need to be able to start the application even if the server is not reachable, Tempo should be able to play already downloaded songs in that case

## Use Case
Tempo should be able to handle unavailable servers and fall back to the downloaded songs.

**Comment by zoidy** [comment]
A related feature would be to be able to add all items in the Download tab to the queue and/or have a button to be able to shuffle all downloaded songs. Right now it's only possible to play them one at a time

**Comment by GallowsDove** [comment]
Thanks for the Feature Request! 

I'd like to point out that Tempo works offline with downloaded songs, and you can play any song/shuffle any album/artist etc.
That being said, I do believe that Shuffle All on all downloaded songs is a very reasonable request. I've created PR with that functionality, marked as draft until layout issues are resolved.

**Comment by CappielloAntonio** [comment]
The pull request has made it into the code, so I can close this issue.
