### ISSUE TITLE
[BUG] - Clean play queue does not remove currently playing song

### ISSUE THREAD

**Issue by Elbullazul** [CappielloAntonio/tempo#133]
## Describe the bug
When opening the play queue and pressing on "Clean play queue", the song currently playing is not removed.

## Expected behavior
Playback should stop and all the songs in the queue should be removed

## Environment
 - Android device: Pixel 4a
 - Android OS version: 13
 - App version: 3.6.0

**Comment by CappielloAntonio** [comment]
No, the behavior is intentional as discussed in https://github.com/CappielloAntonio/tempo/issues/99. 
If you really want to close the music player, simply drag the music player bar down.
