### ISSUE TITLE
[Feature Request] - Remember sort type in "Browse genres" screen

### ISSUE THREAD

**Issue by Elbullazul** [CappielloAntonio/tempo#134]
## Summary
It would be great if the app remembers the sort order when browsing genres in the library tab.

## Description
Currently, if I want to browse in alphabetical order, I have to manually select "Sort by > Name" when opening the "Browse genres". If the app remembers what sort order the user sets, it will reduce friction when browsing genres.

## Use Case
Reduces friction when browsing by genres. It gets a bit frustrating to manually sort by name every time I open the screen.

**Comment by CappielloAntonio** [comment]
Hi @Elbullazul, by default now the genres are sorted alphabetically and I'll overwrite the standard order that the server gives me
