### ISSUE TITLE
[Feature Request] - Option for no screen timeout

### ISSUE THREAD

**Issue by Eschguy** [CappielloAntonio/tempo#135]
## Summary

A toggle in settings that, if enabled, stops the screen from timing out. 

## Use Case
Current vehicle doesn't support Android Auto, so keeping the screen on while playing is a safety/QoL setting.

**Comment by CappielloAntonio** [comment]
Hi @Eschguy,
with the latest update that will be released as soon as possible, I have added an option on the settings page to disable the automatic display shutdown.
