### ISSUE TITLE
Search on top of app doesn't work

### ISSUE THREAD

**Issue by molohov** [CappielloAntonio/tempo#14]
If I try to search for anything using the aforementioned search, it won't return anything. 

If I go into Library, Albums, then search there, it will work. Same with artists

**Comment by CappielloAntonio** [comment]
Hi, can you tell me which server are you using?
I'd like to figure out how to replicate the problem.

**Comment by molohov** [comment]
I'm using Gonic!

**Comment by molohov** [comment]
Tried the new release and it's working well, thank you for the quick fix!
