### ISSUE TITLE
[BUG] - Album art not appearing in Android Auto 

### ISSUE THREAD

**Issue by kaibagley** [CappielloAntonio/tempo#141]
## Describe the bug
Album art doesn't show sometimes on AA sometimes

## Expected behavior
Album art always shows on AA interface

## To Reproduce
1. Plug phone into head unit
2. Open AA
3. Play a song on Tempo
4. No album art

## Environment
 - Android device: Pixel 7 Pro
 - Android OS version: GrapheneOS / AOSP 114
 - App version: 3.6.0

## Logs or Screenshots
Will attach a screenshot soon

## Additional context
Unsure of what exactly causes it, but when I first started using AA with this app I had no problems with art appearing. Will try and provide more information next time I use my car

Album art shows on the bottom dynamic menu thing, just not on the main Tempo app, or when it is split-screened with maps

**Comment by CappielloAntonio** [comment]
Sorry, but without anything to allow me to replicate the issue, it could be anything. I don't think it's a problem with the app as it doesn't repeat itself all the time and anyway, as you said, it worked.
Feel free to reopen this issue and add more details, in order to replicate the problem properly.

**Comment by ejalal** [comment]
Hey  @CappielloAntonio;

I'm having the same issue, album cover shows intermittently, is there anything I can do to provide logs?

Maybe logs from Navidrome would help?

**Comment by janghw4** [comment]
Experiencing same issue with Corolla LE

**Comment by eddyizm** [comment]
This is fixed in the [tempus](https://github.com/eddyizm/tempus/releases/tag/v4.11.0) fork: 

https://github.com/eddyizm/tempus/issues/96#issuecomment-3920812665
