### ISSUE TITLE
[Feature Request] - Delete song from playlist

### ISSUE THREAD

**Issue by wanderer** [CappielloAntonio/tempo#142]
## Summary
It would be nice to be able delete an songs from a playlist.

**Comment by pedrom34** [comment]
You can already do that.
Playlist > modify (from the library screen, not from within the playlist) and swipe left to delete a song.

**Comment by CappielloAntonio** [comment]
As @pedrom34 says in his comment the delete action already exists. it is possible to edit the order of the elements, delete a song within it, edit the name and delete the playlist completely. Just long press on the playlist in question and edit as desired.
