### ISSUE TITLE
[Feature Request] - Add default album layout as settings option

### ISSUE THREAD

**Issue by GallowsDove** [CappielloAntonio/tempo#147]
## Description

I think it'd be nice to have a default album layout be selectable in settings for people who prefer the grid layout.

## Use Case

It's annoying to have to click "Switch Layout" every time if you prefer grid layout for albums at the artist page.

## Additional context

None

**Comment by CappielloAntonio** [comment]
I thought of not inserting a new setting just to select the type of layout of the album list, but of saving the setting and applying the choice to all artist pages.

I do not rule out completely removing the horizontal recycler views in the detail pages in the future, as they are more difficult to scroll and more users are reporting this.

**Comment by GallowsDove** [comment]
Very reasonable, also to put out my two cents, I also agree that grid layouts are more user-friendly than horizontal scrollers, so I would definitely welcome the change.
