### ISSUE TITLE
[Feature Request] - Provide option for designated downloader folder.

### ISSUE THREAD

**Issue by R1D3R175** [CappielloAntonio/tempo#153]
## Summary
Don't use app storage to store downloads but, instead, let the user choose a folder.

## Description
I'd love to download some albums to a folder in order to play them with a local music player (e.g. Poweramp), however since Tempo downloads the songs in its own app storage other apps cannot access it. An option to add the download path and to move already existing songs in the app storage to the designated folder would be pretty great.

## Use Case

It would let the user use whatever player they want, without having to be restricted to Tempo. 

## Additional context
No additional context.

**Comment by CappielloAntonio** [comment]
Hi @R1D3R175, at the moment the music download functionality is entrusted to Exoplayer, a Google library for the use of multimedia content. 

Although in many areas Exoplayer facilitates the work of developing an app like Tempo, in others it can create some problems, such as for downloads. These are managed internally in the library, downloaded from Exoplayer and for Exoplayer as if it were a cache, in a format that only Exoplayer reads.

Although I don't rule out that one day I could go back to working on this functionality (downloading the source file to a location of the user's choice), for the moment I have to leave things as they are.

**Comment by coldshouldermedia** [comment]
This is the reason I am still using Dsub/Ultrasonic.

Tempo seems lovely, but for my usecase, I need access to cached files.
