### ISSUE TITLE
[BUG] - Downloaded songs to an external location don't play

### ISSUE THREAD

**Issue by TacoCake** [CappielloAntonio/tempo#156]
## Describe the bug

When downloading songs with the download location set to `external`, the downloaded songs don't play at all. 
It works as expected when setting the download location to `internal` instead.

## Expected behavior

I expect the downloaded songs to play regardless of where they are saved

## To Reproduce

1. Set download path to external
2. Download some songs
3. Turn off the wifi
4. Try to play any song

## Environment
 - Android device: `Samsung S20 Ultra 5G`
 - Android OS version: `13 (One UI 5.1)`
 - App version: `3.6.0`
 - Other relevant details: `wifi off when attempting playback`

**Comment by CappielloAntonio** [comment]
Hello, can you try this new version of the app and report whether listening to downloads has been fixed?

I tried to reproduce the bug from the emulator on Android Studio, but I can't figure it out, but it could be something connected to some other bug.

Thank you for your patience!

[app-tempo-debug.zip](https://github.com/CappielloAntonio/tempo/files/14077736/app-tempo-debug.zip)

**Comment by TacoCake** [comment]
Hey, thanks for the reply, it does seem to work as expected with the debug APK you sent. Glad to see it's fixed !
