### ISSUE TITLE
[BUG] - Add server popup is not scrollable

### ISSUE THREAD

**Issue by tandy-1000** [CappielloAntonio/tempo#157]
## Describe the bug
The Add server popup is not scrollable which makes it impossible to add a server on small screen devices

## Expected behavior
Reduce screen dpi to a small number

## To Reproduce
Click add server on a small dpi device

## Environment
Xiaomi Qin F21 Pro

To get around this I upped the DPI to get the whole popup to show up.

**Comment by CappielloAntonio** [comment]
Yes, you are absolutely right! 
I fixed it and the fix will be included in the next (I hope soon) release of the app.
