### ISSUE TITLE
[Feature Request] Android Auto Support

### ISSUE THREAD

**Issue by pabloscloud** [CappielloAntonio/tempo#16]

**Comment by molohov** [comment]
Would this effort make Tempo appear as a media player in Google Maps?

**Comment by dfangx** [comment]
Is there any plan to implement this feature? Would love to see this!

**Comment by zachvlat** [comment]
Also I would like that. I could maybe transfer my music library to Jellyfin and have the android auto experience throught their app, but if it's something that could be done for this beautiful app, i would much appreciate the effort!

**Comment by nononolimits** [comment]
Would love this as well.

**Comment by codenamek83** [comment]
I would really appreciate having this as well.

**Comment by kaibagley** [comment]
Any updates on this? Is this a planned feature?

**Comment by zachvlat** [comment]
> Any updates on this? Is this a planned feature?

Graphene OS already implement it.

**Comment by CappielloAntonio** [comment]
You will find Android Auto support with the latest version of Tempo that has just been released

**Comment by kaibagley** [comment]
Wow, you are amazing. Thanks for making the best music app

**Comment by pabloscloud** [comment]
> You will find Android Auto support with the latest version of Tempo that has just been released

awesome, thanks!
