### ISSUE TITLE
[Question] unknown fork on fdroid

### ISSUE THREAD

**Issue by back-lacking** [CappielloAntonio/tempo#161]
https://www.f-droid.org/en/packages/com.cappielloantonio.notquitemy.tempo/ i found this in fdroid, and im wordering whether or not this is a well known fork of tempo using the same name for some reason (and probably not malicious) or is something else. The first version of this thing is 3.7.0 and i cant seem to find links to the source code or github repo.

**Comment by MCBOi64** [comment]
That is not a fork of Tempo and it actually is the official version. CappielloAntonio just recently made a [Metadata Merge Request](https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14434#note_1747916078) to the main F-Droid repository. The link to the GitHub source code can be found in the license section on the page.
![Source_Code.png](https://github.com/CappielloAntonio/tempo/assets/67389582/11c7ebaf-ad84-41d3-930d-c9bf7f31b85d)

**Comment by CappielloAntonio** [comment]
Yes, that was me. I finally managed to get it done.
