### ISSUE TITLE
[Feature Request] - Change order of Homescreen items.

### ISSUE THREAD

**Issue by 1tituz** [CappielloAntonio/tempo#163]
It would be great to be able to change the order of the Elements on the Homescreen.
For instance, for me it would be nice to have to "Recently added" Section right at the top of the Homescreen when you open the App.
That way the user experience could be a lot more personalized.

Well, just want to put it out there.
Thanks for the already best Subsonic App out there!!

**Comment by ryankupk** [comment]
+1, also settings for hiding/showing elements on the home page

**Comment by CappielloAntonio** [comment]
I am closing this issue as the functionality was implemented in the March update.
