### ISSUE TITLE
[BUG] - .flac 1625 kbps track is not played

### ISSUE THREAD

**Issue by wazolab** [CappielloAntonio/tempo#166]
## Describe the bug
My .flac 1625 kbps track isn't played at all. But I can play it on my Navidrome server.
Other .flac let's say 817 kbps are played nicely.

## Expected behavior
I would expect .flac 1625 kbps to work on Tempo app unless not compatible somehow ?

## Environment
 - Android device: Xiaomi Redmi Note 5
 - Android OS version: Android 9
 - App version: 3.6.0

## Logs or Screenshots
![WhatsApp Image 2024-02-09 at 3 11 46 PM](https://github.com/CappielloAntonio/tempo/assets/38253764/818ba2e4-38ee-41e9-b5f8-bfa92e460e51)

**Comment by CappielloAntonio** [comment]
Yes, high bitrate should not be an issue. To demonstrate this, I tried to play a track with a bitrate of 1762kbps and everything went smoothly. Are you sure the file isn't the problem? Is the server logging anything meaningful?

![Screenshot_20240219-095209_Tempo](https://github.com/CappielloAntonio/tempo/assets/14802539/593efb93-0e75-4345-8cd2-a2ea151cfe40)

**Comment by wazolab** [comment]
Here is the log when I'm trying to play from Tempo App (which doesn't work):
```
Feb 19 10:33:55INFO[48307] Streaming file artist=Vald bitRate=0 cached=false format=raw originalBitRate=1625 originalFormat=flac requestId=a0ad86d6-7d39-44ca-a886-10e4822f4d91/XqhMj4bJnq-005115 title=FORFAIT transcoding=false user=**** username=****

```

Here is the log when I play the same song from Navidrome UI:
```
Feb 19 10:36:23INFO[48456] Now Playing artist=Vald player="NavidromeUI [Chrome/Linux]" requestId=a0ad86d6-7d39-44ca-a886-10e4822f4d91/XqhMj4bJnq-005144 title=FORFAIT user=**** username=****
Feb 19 10:36:23INFO[48456] Streaming file artist=Vald bitRate=0 cached=false format=raw originalBitRate=1625 originalFormat=flac requestId=a0ad86d6-7d39-44ca-a886-10e4822f4d91/XqhMj4bJnq-005145 title=FORFAIT transcoding=false user=**** username=****

```

**Comment by CappielloAntonio** [comment]
> For info the whole album isn't working on Tempo App, but does work on Navidrome Web UI ... I could send you a track file if you want ? Maybe here: https://www.sharedrop.io/rooms/d245aeac-b575-417c-8c8e-89c1d4b6a932

Yes please. Even a single track.

**Comment by wazolab** [comment]
> > For info the whole album isn't working on Tempo App, but does work on Navidrome Web UI ... I could send you a track file if you want ? Maybe here: https://www.sharedrop.io/rooms/d245aeac-b575-417c-8c8e-89c1d4b6a932
> 
> Yes please. Even a single track.

as soon as you connect to P2P link I'll drop the file then

**Comment by CappielloAntonio** [comment]
Ook, I'm a Reliable Bear

**Comment by wazolab** [comment]
> Ook, I'm an Enthusiastic Penguin

Sorry I was out for a while, waiting in the room as Charming Sheep

**Comment by CappielloAntonio** [comment]
Okay, now I can run some tests.

**Comment by CappielloAntonio** [comment]
Really strange, I can play the song without any problem. I can stop, jump from one point to another, go forward and backward. If you want, and you're free to say no, we can try directly with your server. You can create me a test user, and give me limited access for a few minutes, just long enough to debug the problem.

![Screenshot_20240219-140834_Tempo](https://github.com/CappielloAntonio/tempo/assets/14802539/2829d238-2589-44b8-afc3-df1f755ff9dd)

**Comment by wazolab** [comment]
Alright ... indeed very strange ...
Here is an account to my server: https://music.wazo-lab.io/
username: antonio-capiello
password: testpassword

**Comment by CappielloAntonio** [comment]
Okay, thanks so much! You can now delete the message and message history with your credentials. As soon as I can I will test on your server.

**Comment by CappielloAntonio** [comment]
I actually did a quick test with the affected songs. As you can also see from the logs, the song is from the same album, and on my device it seems to run without any problems.

![Screenshot_20240219-144207_Tempo](https://github.com/CappielloAntonio/tempo/assets/14802539/01bb7bab-b2ec-4996-abb5-5c402387c6e4)

Now I don't know if I should blame the server or the device. Is there any way to try the app on a device other than yours?

**Comment by CappielloAntonio** [comment]
[This section](https://developer.android.com/media/media3/exoplayer/troubleshooting#video-playback-is-stuttering) on Media3 library's troubleshooting page may be related to your problem.
They talk about video, but the problem could also extend to high bitrate audio files.

**Comment by wazolab** [comment]
If I constraint Navidrome with transcoding OPUS - 128kps and set the same in Tempo (maybe it's useless as the server decides what to share with the client), it WORKS !
Then it looks like a device limitation.

**Comment by CappielloAntonio** [comment]
It makes sense, after excluding apps and servers the problem had to be elsewhere.
I'm closing this issue then, feel free to reopen it should there be any other problems related to it.
