### ISSUE TITLE
[Feature Request] Transitions between Tracks

### ISSUE THREAD

**Issue by DoM1niC** [CappielloAntonio/tempo#167]
## Summary
A nice Option will be to fade/In/Out between Tracks

## Description
This can be a Option to make a time in seconds configurable

## Use Case
Tracks are mixed in next to the tracks in the playlist.

**Comment by CappielloAntonio** [comment]
I'm sorry, but I don't think I'll implement this feature as I've never appreciated this kind of effects on music tracks. I don't rule out the possibility that I might go back to work on it one day.
