### ISSUE TITLE
[Feature Request] Make searched Items sortable

### ISSUE THREAD

**Issue by DoM1niC** [CappielloAntonio/tempo#168]
## Summary
Make searched Items sortable

## Description
Add a small row to filter searched elements better to find the correct one like added from date or other attributes ascending 
 and descending from the file or metedata.

## Use Case
If you search a track and the list is very huge to find the correct one.

**Comment by CappielloAntonio** [comment]
Feature difficult to implement as the items are never passed to me in their entirety so as not to weigh down and slow down the app. In [search](https://www.subsonic.org/pages/api.jsp#search3), it is the server that, starting from a search string, returns me the results. The only other accepted parameter is the count of returned items.
