### ISSUE TITLE
[Feature Request] - Synchronize Loved Tracks ❤️

### ISSUE THREAD

**Issue by justblue19** [CappielloAntonio/tempo#170]
## Summary
I suggest adding synchronization for loved tracks in Tempo with Navidrome/Subsonic.
## Description
While Tempo currently supports synchronization for scrobbling, incorporating the ability to sync loved tracks would significantly enhance the user experience by ensuring consistent reflection of favorite songs between Tempo and Navidrome/Subsonic.
## Use Case
Many users, myself included, heavily rely on the loved tracks feature in Tempo, using it to automatically download and have their favorite songs available on their mobile devices, especially when lacking a connection to the server. By expanding synchronization capabilities to include loved tracks, Tempo can better cater to users like me who prioritize this functionality.
## Additional context
The integration of loved tracks synchronization would not only strengthen the connection between Tempo and the server but also provide users with a more comprehensive and personalized music library. This feature could be particularly beneficial for users who frequently switch between a laptop and smartphone for music listening. Additionally, it would complement the existing scrobbling integration, creating a more cohesive and feature-rich music experience within Tempo.

**Comment by justblue19** [comment]
I just wanted to take a moment to express my sincere appreciation to Antonio Cappiello for creating this amazing opensource music client. Tempo has become my go to alternative to mainstream platforms, and it's genuinely user friendly.. a game changer!
In my opinion, Tempo surpassed Spotify in certain aspects. 
Thank you for your hard work and commitment to making Tempo an exceptional music app. 
Looking forward to the continued success and growth of this project!

**Comment by justblue19** [comment]
Yes, I'm Dumb.

**Comment by emes81** [comment]
I'm wondering why this was closed as completed?
I use Tempo with Navidrome, currently starred albums in Tempo aren't reflected as as favourites in Navi. Favourited songs also don't seem to be reflected.
Would it be technically feasible to implement sync of favourites/starred items?

**Comment by curiousercreative** [comment]
I just installed v3.7.0 via F-Droid and the state of whether a track or album is starred/like/favorited synced well for me.
