### ISSUE TITLE
[Feature Request] - Continuous playback

### ISSUE THREAD

**Issue by TacoCake** [CappielloAntonio/tempo#179]
## Summary

I would love a way be able to start a song, put my phone away, and have tempo automatically pick out other songs to listen to. 

## Description

I think it should pick songs based on similarity (artist, genre, mood, etc). Would love to have it on by default or at least be a toggle in the settings.

## Use Case

This would be helpful for long car drives and working without having to constantly pick a new song.

## Additional context

Spotify, if I recall correctly, does this currently

**Comment by CappielloAntonio** [comment]
Hi, I added a setting called Continuous Play which, if enabled, allows music to continue playing even when a playlist or album is finished. it is a setting that is active by default but which you can deactivate as you may prefer not to exaggerate in data consumption. 

The feature still needs to be fully tested before we can release it, but you can test this new version if you prefer. I'm closing this issue, but feel free to reopen it or open a new one if you encounter any problems.

[app-notquitemy-debug.zip](https://github.com/user-attachments/files/15526288/app-notquitemy-debug.zip)
