### ISSUE TITLE
[Feature Request] - Add sort by Recently Added into Albums sort options

### ISSUE THREAD

**Issue by v4rakh** [CappielloAntonio/tempo#181]
## Summary

Add sort by Recently Added in Albums sort view drop down menu.

## Description

* Add Recently Added as a sort direction in the Albums view drop down
* Should sort by descending, so latest added album is on top

## Use Case

Currently, there's limited visibility of recently added albums in reverse chronological order. At least I am a heavy user of this feature everywhere, mostly having a view listening/downloading latest albums I added to my library would have a huge benefit.  

## Additional context

Add this as a sort option in the drop-down.

![Screenshot_20240304-183754_1](https://github.com/CappielloAntonio/tempo/assets/55667263/3ca873d2-5f83-4db7-965a-aad62d422376)

**Comment by CappielloAntonio** [comment]
New sorting type added, it will be available starting from the next version!

![Screenshot_20240316-162227_Tempo](https://github.com/CappielloAntonio/tempo/assets/14802539/0976c567-7fe4-43bc-a8db-f1b07bea0eab)
