### ISSUE TITLE
[Feature Request] - updating app on izzyondroid

### ISSUE THREAD

**Issue by back-lacking** [CappielloAntonio/tempo#183]
## Summary
updating app on izzyondroid pls

## Description
what the tin says
fdroid is 3.6.0 while izzyondroid is 3.7.0. pls update

## Use Case
dont really want to reinstall to the fdroid version and then reconfigure the app

**Comment by CappielloAntonio** [comment]
The app will be updated soon, version 3.7.0 was created specifically for release on F-Droid, but it doesn't add much that isn't already in 3.6.0
