### ISSUE TITLE
[Feature Request] - Album length on preview page

### ISSUE THREAD

**Issue by twoloavesofbread** [CappielloAntonio/tempo#185]
## Summary
Show album length on Album preview page

## Description
Show the length in HH:MM:SS on the preview page for an Album, next to the year released.

## Use Case
This feature would allow users to see how long it would take for an album to finish, just like they're already able to see with songs and playlists. This allows the user to estimate the end time of an album or, in the absence of continuous playback, determine an approximate time to queue the next set of tracks.
 
## Additional context
I don't use playlists, but I presume this feature would also be of potentially even greater value on a playlist preview page as a management feature, since it would allow the user to determine if their playlist is of appropriate/desired length. Apologies if it's already included there. Album & playlist length are a mainstay feature of modern media players, such as Spotify, Symfonium, and Navidrome's web interface.

(**Edit:** Upon making a playlist for testing purposes, I see that duration is listed on a playlist's preview page. Nice!)

## Original vs. Mockup
Below is a quick mockup of what the feature could look like. Using the bullet as the center point retains visual consistency & has a similar level of information density with the tracks below. You could also simply center the text and not use the bullet as an anchor point.

Original:
<img src="https://github.com/CappielloAntonio/tempo/assets/46307093/3b9b16bd-7c0f-4116-962f-e2c38f8e9196" width="400">

Mockup:
<img src="https://github.com/CappielloAntonio/tempo/assets/46307093/f051ae49-927f-4b0a-9884-7782883fa967" width="400">

**Comment by CappielloAntonio** [comment]
Not a bad idea, I was thinking of implementing it like this:
![Screenshot_20240316-154301_Tempo](https://github.com/CappielloAntonio/tempo/assets/14802539/53f5b5bc-c91d-471b-b83b-a160a73d8bc9)
