### ISSUE TITLE
Feature Request: Queue 

### ISSUE THREAD

**Issue by IceWreck** [CappielloAntonio/tempo#19]
Spotify, DSub etc all have a play queue that you can sort, add songs to, remove, etc. Would love it if tempo had one too.

PS: thanks for making this

**Comment by CappielloAntonio** [comment]
Hi, maybe in a future update I'll have to make it flashier, but Tempo supports viewing the play queue.  

Just swipe up on the music player at the bottom to bring up the full screen music player and then swipe up again.

**Comment by IceWreck** [comment]
Ahh I found it. Thanks, this will do.

Can you add a remove from queue / clear queue button in the future ?

**Comment by CappielloAntonio** [comment]
You can swipe laterally on a item to remove it or long tap and move to rearrange the playing queue

**Comment by IceWreck** [comment]
Thanks. I tried before,  but I was swiping in the other direction.

**Comment by dnno** [comment]
This works great, but it isn't obvious how to so this. Is there something like a feature documentation already? I'd be happy to help write it, as far as Iam familiar with the features...

**Comment by CappielloAntonio** [comment]
I am writing it myself, in order to be as complete as possible and not to forget anything. 
The gestures have been introduced over the course of three years or so, some small ones I use so rarely that I have almost forgotten them.
