### ISSUE TITLE
[Feature Request] - Show rating instead of heart/favorite

### ISSUE THREAD

**Issue by dessalines** [CappielloAntonio/tempo#199]
## Summary

When looking either at a playlist, or the currently playing song, it'd be nice to be able to see the song rating. This is possible both on ultrasonic and dsub.

## Description

Add a setting to show rating instead of favorite.

## Use Case

When looking at an album, I'd like to see the songs I've rated, so I can quickly remove the ones I didn't like. Right now, I have to click and hold the favorite button on every song just to see this info.

## Additional context

N/A

**Comment by TheNomad11** [comment]
With version 3.8 you can view the rating when you search for the song but not when the song is playing

**Comment by dessalines** [comment]
Oops, didn't see the setting. Thanks!
