### ISSUE TITLE
Crash on opening subsonic server

### ISSUE THREAD

**Issue by Mihara** [CappielloAntonio/tempo#2]
I happen to have my subsonic server in a subdirectory, `https://example.com/navidrome`, which tends to uncover problems in early versions of players.

1. Omitting `https://` - that is, writing `example.com/navidrome` - outright causes a crash.
2. `https://example.com/navidrome` results in a quickly flashing error message about an IllegalStateException at line 1. Same if I add a trailing slash.

**Comment by ivan-avalos** [comment]
The `IllegalStateException` happens to me too, even though mine is not on a subdirectory. What server are you using? I'm using Supysonic 0.7.2 (the latest in Debian).

**Comment by CappielloAntonio** [comment]
The second release should have fixed the crash problem and in theory the second point as well.
In case there are other problems related to the previous two points, feel free to reopen this issue!
