### ISSUE TITLE
Feature Request: Synced Lyrics

### ISSUE THREAD

**Issue by IceWreck** [CappielloAntonio/tempo#20]
I just discovered that this has lyrics too, nice !

But they're not synced i.e. current line doesn't get highlighted / scrolled. Would love that.

**Comment by CappielloAntonio** [comment]
It's a good idea and would also be nice to implement.
Correct me if I'm wrong, but I don't think the Subsonic API is meant to have lyrics in sync. 
I would gladly work on this feature but Gonic and Navidrome, my two reference servers, return me the lyrics in plain text.

**Comment by IceWreck** [comment]
I am not familiar with subsonic's API but at a quick glance the endpoint does not distinguish between synced and unsynced lyrics.

https://opensubsonic.netlify.app/docs/endpoints/getlyrics/

However, Navidrome's Web UI and the Feishin desktop client both implement synced lyrics.

I think navidrome is returning lyrics in the synced lyrics format with the `getlyrics` endpoint where possible.
```
[00:02.78]XYZ
[00:07.53]FOO BAR
[00:12.69]Something
[00:15.20]Whatever
[00:17.65]A bunch of other words
```
and the clients are just parsing it and displaying the current line based on the position of the playback cursor.

https://github.com/jeffvli/feishin/blob/8e83beffcc01759cb92701b2079495afa033dc97/src/renderer/features/lyrics/queries/lyric-query.ts

https://github.com/jeffvli/feishin/blob/8e83beffcc01759cb92701b2079495afa033dc97/src/renderer/features/lyrics/synchronized-lyrics.tsx#L45


Maybe @jeffvli or @deluan can confirm ?

**Comment by IceWreck** [comment]
So I just checked with curl and I'm getting unsynced lyrics via `getlyrics`.

Its probably a navidrome specific endpoint then.

**Comment by IceWreck** [comment]
So i checked it out. Its a Navidrome  API.

`GET https://music.example.com/api/song/95abe070128d9e53ec00f3d2e2757efa`

```
{
	"playCount": 3,
	"playDate": "2023-07-29T17:32:34Z",
	"rating": 0,
	"starred": false,
	"starredAt": "0001-01-01T00:00:00Z",
	"bookmarkPosition": 0,
	"id": "95abe070128d9e53ec00f3d2e2757efa",
	"path": "/music/Main/June 2023/Conor Maynard - How Am I.ogg",
	"title": "How Am I",
	"album": "+11 Hours",
	"artistId": "bdec3e6fe01cb386932946e45e641562",
	"artist": "Conor Maynard",
	"albumArtistId": "bdec3e6fe01cb386932946e45e641562",
	"albumArtist": "Conor Maynard",
	"albumId": "de425119ca5f4557bf3afeddb7bbb126",
	"hasCoverArt": true,
	"trackNumber": 6,
	"discNumber": 1,
	"year": 2023,
	"size": 9215592,
	"suffix": "ogg",
	"duration": 209.64,
	"bitRate": 343,
	"channels": 2,
	"genre": "",
	"genres": null,
	"fullText": " +11 am conor hours how i maynard",
	"orderTitle": "How Am I",
	"orderAlbumName": "+11 Hours",
	"orderArtistName": "Conor Maynard",
	"orderAlbumArtistName": "Conor Maynard",
	"compilation": false,
	"lyrics": "[00:09.65]Tell me why I dreamt last night that you came back\n[00:12.55]And we were doing fine? (Say oh)\n[00:17.95]When I know that you would only hurt me\n[00:20.85]If you came back in my life (say oh)\n[00:25.58]Oh, why'd you tear my heart out without even saying why? No\n[00:34.92]'Cause now it feels like all that you said to me was just a lie (say oh)\n[00:43.72]How am I, how am I supposed to trust somebody else again? (Say oh)\n[00:53.30]How am I, how am I supposed to love somebody else again? (Say oh)\n[01:01.68]Did you change your mind, or did you never mean it?\n[01:06.53]I thought you were mine, but you left me to bleed\n[01:10.90]How am I, ow am I supposed to trust somebody else again? (Say oh)\n[01:20.23]Tell me what they said, when we were talking\n[01:22.94]You were with another guy (say oh)\n[01:28.88]Maybe that explains why when you left\n[01:31.67]You couldn't look me in my eye, say oh\n[01:37.50]Ooh\n[01:38.19]Why'd you tear my heart out without even saying why?\n[01:43.53]No, no, no, no\n[01:46.47]'Cause now it feels like all that you said to me was just a lie (say oh)\n[01:54.46]How am I, how am I supposed to trust somebody else again? (Say oh)\n[02:04.15]How am I, how am I supposed to love somebody else again? (Say oh)\n[02:12.53]Did you change your mind, or did you never mean it?\n[02:17.76]I thought you were mine, but you left me to bleed\n[02:21.84]How am I, how am I supposed to trust somebody else again? (Say oh)\n[02:30.40]Did you change your mind, or did you never mean it?\n[02:35.26]I thought you were mine, but you left me here bleeding\n[02:39.97]You only just got here, you're already leaving my life (say oh)\n[02:48.71]How am I, how am I supposed to trust somebody else again? Oh, no (say oh)\n[02:56.58]No, how am I (how am I)\n[02:59.15]How am I supposed to love somebody else again? (Say oh)\n[03:05.91]Did you change your mind or (did you)\n[03:09.30]Did you never mean it? (Tell me, did you mean it)\n[03:11.21]I thought you were mine, but you left me to bleed\n[03:15.37]How am I (how am I)\n[03:17.59]How am I supposed to trust somebody else again? (Say oh)\n[03:22.40]",
	"rgAlbumGain": 0,
	"rgAlbumPeak": 1,
	"rgTrackGain": 0,
	"rgTrackPeak": 1,
	"createdAt": "2023-06-30T19:02:08.049332447Z",
	"updatedAt": "2023-07-29T06:01:39.039289295Z"
}
```

**Comment by CappielloAntonio** [comment]
That's right, unfortunately it is something internal to Navidrome and therefore does not currently meet any standard of the Subsonic server family. I want to stick to the official API as much as possible, even for song lyrics.

The good news is that the OpenSubsonic project exists and could do something to enhance the Subsonic API and, in this case, allow the user to choose between the lyrics or the synchronized lyrics.

**Comment by IceWreck** [comment]
Fair enough

**Comment by deluan** [comment]
This will soon be a feature in OpenSubsonic compatible servers:
- [getLyricsBySongId](https://opensubsonic.netlify.app/docs/endpoints/getlyricsbysongid/)
- https://github.com/navidrome/navidrome/pull/2656
