### ISSUE TITLE
[Feature Request] - Deploy on Google Play Store

### ISSUE THREAD

**Issue by black00019** [CappielloAntonio/tempo#206]
## Summary
Download Tempo from Google Play Store?
Thanks for beautiful App!!!

**Comment by black00019** [comment]
Hi @CappielloAntonio , were you able to publish the app on the google play store?, that would be great

**Comment by CappielloAntonio** [comment]
In the future it will also arrive on the Play Store, to make testing easier thanks to crashlytics. But not immediately.
