### ISSUE TITLE
[Feature Request] - Use discnumber in downloaded albums

### ISSUE THREAD

**Issue by carnager** [CappielloAntonio/tempo#207]
## Summary
While multi-disc albums work perfectly fine in normal library, for downloaded albums all titles are only sorted by tracknumber, but not by disc.

It would be nice, if Tempo actually used the discnumber tag for sorting locally stored albums.

## Use Case
Since albums are often meant to be listened to front-to-back this missing feature is a bit of a dealbreaker for album lovers.

**Comment by CappielloAntonio** [comment]
Hi @carnager,
I solved the sorting problem and you can test it with this apk. 
Soon I will release a new version with the fix.

[app-notquitemy-debug.zip](https://github.com/CappielloAntonio/tempo/files/15445094/app-notquitemy-debug.zip)

**Comment by carnager** [comment]
This works, but the debug apk crashes, when i search for stuff in normal library and then enter a release.
