### ISSUE TITLE
Fastlane: changelog too long

### ISSUE THREAD

**Issue by IzzySoft** [CappielloAntonio/tempo#209]
Please be aware that per-release changelogs with Fastlane are limited to 500 chars (`25.txt` has more than 800). Everything behind that position will simply be truncated, even mid-word. Which means the current one ends with "Implemented shuffle feature for ".

Tipp: stick to the essentials there, and link to a "full changelog" when needed (mentioning its URL) – like `full changelog at https://github.com/CappielloAntonio/tempo/releases/tag/3.8.0`.

Thanks!

**Comment by CappielloAntonio** [comment]
Hi @IzzySoft, sorry I didn't know about that!
I will pay more attention to future releases following your advice. 
Is there anything I can do now to fix it?

**Comment by IzzySoft** [comment]
Just take care for the next one. For this one, I've fixed it locally here as described above.

As you weren't aware, I'll leave you the link to my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) so you can check for the other limits (and maybe what else you'd like to add, e.g. a featureGraphic if you like – that would be shown as headers with the app details in the client). E.g.: shortdesc max 80 chars, fulldesc max 4,000, and certain image sizes.
