### ISSUE TITLE
[Feature Request] - Android Auto

### ISSUE THREAD

**Issue by tamimology** [CappielloAntonio/tempo#212]
## Summary
Android Auto integration 

## Description
When connecting the phone via USB and using Android Auto, I can't see the app in the list. 

Also when using the location, it doesn't show the track name/controls compared when using maps by itself 

## Use Case
Easier to control and see tracks while driving using Android Auto, rather than unlocking the phone everytime needed while driving 

## Additional context
N/A

**Comment by Kirk1984** [comment]
I just want to confirm. It doesn't show on my Car (also via USB Cable like OP) and I can't add it to the Launcher via the Android Auto Settings on my Phone. Only other 3rd Party app I use via android auto is TomTom Amigo and that works.

**Comment by Kirk1984** [comment]
Enabling dev mode and allow apps from unknown sources did it. Thanks!

**Comment by tamimology** [comment]
Can someone guide me on how to do these 2 steps? I couldn't find how yet

**Comment by atmurr** [comment]
> Can someone guide me on how to do these 2 steps? I couldn't find how yet

This is on GrapheneOS, I assume the steps would be the same on other Android versions: Go to Settings > Apps > Android Auto > 'Additional settings in the app' > Scroll down to "Version and permission info" and tap that box 10 times or until it tells you you're in developer mode. Then click the ... menu in the top right > Developer settings > Check "Unknown sources". 

Tempo should show up in Android Auto after that.

**Comment by tamimology** [comment]
> > Can someone guide me on how to do these 2 steps? I couldn't find how yet
> 
> This is on GrapheneOS, I assume the steps would be the same on other Android versions: Go to Settings > Apps > Android Auto > 'Additional settings in the app' > Scroll down to "Version and permission info" and tap that box 10 times or until it tells you you're in developer mode. Then click the ... menu in the top right > Developer settings > Check "Unknown sources". 
> 
> Tempo should show up in Android Auto after that.

Thanks mate. This did the job and can confirm it is working fine with me now🤗

**Comment by ahmadyusuf** [comment]
It is strange because if I download Tempo from F-Droid, the application icon color is Blue and it does not work with Android Auto, it shows up but when selected, it opens a black screen.
Hoever, if I download from Github directly, the application icon color is the normal Tempo icon and it works perfectly with Android Auto , both applications from F-Droid and Github have the same version of 3.8.1
