### ISSUE TITLE
[BUG] - Song titles surrounded by `<>` don't display in Tempo

### ISSUE THREAD

**Issue by atmurr** [CappielloAntonio/tempo#213]
## Describe the bug
Songs with titles like `<example>` don't display properly in Tempo, the name isn't shown. For a real song example, `Motionless In White - </c0de>`

## Expected behavior
The name of the song displays in plain text, like in the Navidrome webui:

![image](https://github.com/CappielloAntonio/tempo/assets/88594233/e4b1afa3-8c8e-471a-abe2-678964eee737)

## To Reproduce
1. Have a song in your library titled `<something>`
2. View it in Tempo
3. Name doesn't display in library or player (in app or Android Auto)

<img src="https://github.com/CappielloAntonio/tempo/assets/88594233/d16ec320-485a-4f92-a874-99d795658787" width="400" />

## Environment
 - Android device: Pixel 8 Pro
 - Android OS version: Android 14 (GrapheneOS)
 - App version: 3.8.1

## Additional context
I created some test files with weird names, here's the result of that.

Navidrome webui:

![image](https://github.com/CappielloAntonio/tempo/assets/88594233/c12b0d84-dec4-4d93-ad4e-628837c15010)

Tempo:

<img src="https://github.com/CappielloAntonio/tempo/assets/88594233/49ca2258-eabf-4d89-bfa7-938439bd057a" width="400" />

**Comment by GallowsDove** [comment]
I did some testing and you're right, it seems to be caused by `Html.fromHtml` removing all tags. However I'm not sure why that's even used to preprocess all titles before displaying them, so I would need CappielloAntonio to elaborate on that.

**Comment by CappielloAntonio** [comment]
Good question, although now I don't even remember the reason for that check. I agree, it was too strong and invasive, but in its invasiveness it checked several strings that could pass as null and cause exceptions. Now I've eliminated the string rework almost everywhere, leaving it only for descriptions and in notes, often taken from last.fm and therefore more likely to contain dirty text. We'll see how it goes, but I expect an increase in crash cases.

Here is a test apk to test the fix.

[app-notquitemy-debug.zip](https://github.com/CappielloAntonio/tempo/files/15445157/app-notquitemy-debug.zip)
