### ISSUE TITLE
[BUG] - Navidrome server by IP - Wrong username or password

### ISSUE THREAD

**Issue by Aphyxia** [CappielloAntonio/tempo#217]
## Describe the bug
Added a Navidrome server by IP http://xxx.xxx.xxx.xxx:4533 with the correct username and password but it does not connect and gives error 40 Wrong username or password. Low security checkbox doesn't change a thing.
Same data works on browser and the Symfonium app.

## Environment
 - Android device: Xiaomi Poco X3 NFC
 - Android OS version: 12 SKQ1.211019.001
 - App version: 3.8.1

**Comment by CappielloAntonio** [comment]
I would need some logs to try to understand why this behavior occurs. With the same setup I don't have this problem, so it could be something quite "unique". If you are not able to capture an error log I can also connect to your server with a user created ad-hoc by you and investigate.

In case you want to try to capture the logs during login you can do it with this apk:
[app-notquitemy-debug.zip](https://github.com/CappielloAntonio/tempo/files/15447642/app-notquitemy-debug.zip)

**Comment by ptartari** [comment]
Hi to all!
I probably have the same problem too.
Using a Samsung J5 with Android 9 I can connect with the Navidrome server I have installed in my home, but with a Samsung TAB A9 with Android 14 I get the error: “40 - Wrong username or password”.

This is the output of the “journalctl -f” command with Android 14 [ko]

Jul 24 21:28:18 MusikONE navidrome[439]: time="2024-07-24T21:28:18+02:00" level=debug msg="API: New request /rest/ping" client=Tempo requestId=MusikONE/JMrCnT9dZZ-000745 username=musikone version=1.15.0
**Jul 24 21:28:18** MusikONE navidrome[439]: time="2024-07-24T21:28:18+02:00" level=warning msg="API: Invalid login" auth=subsonic error="data not found" remoteAddr="192.168.33.118:49958" requestId=MusikONE/JMrCnT9dZZ-000745 username=musikone
**Jul 24 21:28:18** MusikONE navidrome[439]: time="2024-07-24T21:28:18+02:00" level=warning msg="API: Invalid login" auth=subsonic error="invalid authentication" remoteAddr="192.168.33.118:49958" requestId=MusikONE/JMrCnT9dZZ-000745 username=musikone
**Jul 24 21:28:18** MusikONE navidrome[439]: time="2024-07-24T21:28:18+02:00" level=warning msg="API: Failed response" endpoint=/rest/ping error=40 message="Wrong username or password" requestId=MusikONE/JMrCnT9dZZ-000745
**Jul 24 21:28:18** MusikONE navidrome[439]: time="2024-07-24T21:28:18+02:00" level=debug msg="HTTP: GET http://192.168.44.7:4533/rest/ping?s=[REDACTED]&c=Tempo&t=[REDACTED]&u=musikone&v=1.15.0&f=json" elapsedTime="913.344µs" httpStatus=200 remoteAddr="192.168.33.118:49958" requestId=MusikONE/JMrCnT9dZZ-000745 responseSize=194 userAgent=okhttp/5.0.0-alpha.12

And this is the output using Android 9 [ok]

**Jul 24 22:00:34** MusikONE navidrome[439]: time="2024-07-24T22:00:34+02:00" level=debug msg="API: New request /rest/ping" client=Tempo requestId=MusikONE/JMrCnT9dZZ-000822 username=musikone version=1.15.0
**Jul 24 22:00:34** MusikONE navidrome[439]: time="2024-07-24T22:00:34+02:00" level=warning msg="API: Invalid login" auth=subsonic error="data not found" remoteAddr="192.168.33.117:46796" requestId=MusikONE/JMrCnT9dZZ-000822 username=musikone
**Jul 24 22:00:34** MusikONE navidrome[439]: time="2024-07-24T22:00:34+02:00" level=info msg="Registering new player" client=Tempo id=6b8b0dca-7f97-49b7-acf2-30ad7caea69b requestId=MusikONE/JMrCnT9dZZ-000822 type=okhttp username=musikone
**Jul 24 22:00:34** MusikONE navidrome[439]: time="2024-07-24T22:00:34+02:00" level=error msg="SQL: `INSERT INTO player (client,id,ip_address,last_seen,max_bit_rate,name,report_real_path,scrobble_enabled,transcoding_id,user_agent,user_name) VALUES ({:p0},{:p1},{:p2},{:p3},{:p4},{:p5},{:p6},{:p7},{:p8},{:p9},{:p10})`" args="map[p0:Tempo p1:6b8b0dca-7f97-49b7-acf2-30ad7caea69b p10:musikone p2:192.168.33.117 p3:2024-07-24T22:00:34.495911603+02:00 p4:0 p5:Tempo [okhttp] p6:false p7:true p8: p9:okhttp]" elapsedTime="52.053µs" error="FOREIGN KEY constraint failed" requestId=MusikONE/JMrCnT9dZZ-000822 rowsAffected=0
**Jul 24 22:00:34** MusikONE navidrome[439]: time="2024-07-24T22:00:34+02:00" level=error msg="Could not register player" client=Tempo error="FOREIGN KEY constraint failed" requestId=MusikONE/JMrCnT9dZZ-000822 username=musikone
**Jul 24 22:00:34** MusikONE navidrome[439]: time="2024-07-24T22:00:34+02:00" level=debug msg="API: Successful response" endpoint=/rest/ping requestId=MusikONE/JMrCnT9dZZ-000822 status=OK
**Jul 24 22:00:34** MusikONE navidrome[439]: time="2024-07-24T22:00:34+02:00" level=debug msg="HTTP: GET http://192.168.44.7:4533/rest/ping?s=[REDACTED]&c=Tempo&t=[REDACTED]&u=musikone&v=1.15.0&f=json" elapsedTime=1.6ms httpStatus=200 remoteAddr="192.168.33.117:46796" requestId=MusikONE/JMrCnT9dZZ-000822 responseSize=131 userAgent=okhttp/5.0.0-alpha.12
**Jul 24 22:00:34** MusikONE navidrome[439]: time="2024-07-24T22:00:34+02:00" level=debug msg="API: New request /rest/getStarred2" client=Tempo requestId=MusikONE/JMrCnT9dZZ-000823 username=musikone version=1.15.0
**Jul 24 22:00:34** MusikONE navidrome[439]: time="2024-07-24T22:00:34+02:00" level=warning msg="API: Invalid login" auth=subsonic error="data not found" remoteAddr="192.168.33.117:46800" requestId=MusikONE/JMrCnT9dZZ-000823 username=musikone
**Jul 24 22:00:34** MusikONE navidrome[439]: time="2024-07-24T22:00:34+02:00" level=info msg="Registering new player" client=Tempo id=381bbd09-d6e1-4d1c-aa86-e03349bd9de5 requestId=MusikONE/JMrCnT9dZZ-000823 type=okhttp username=musikone
**Jul 24 22:00:34** MusikONE navidrome[439]: time="2024-07-24T22:00:34+02:00" level=error msg="SQL: `INSERT INTO player (client,id,ip_address,last_seen,max_bit_rate,name,report_real_path,scrobble_enabled,transcoding_id,user_agent,user_name) VALUES ({:p0},{:p1},{:p2},{:p3},{:p4},{:p5},{:p6},{:p7},{:p8},{:p9},{:p10})`" args="map[p0:Tempo p1:381bbd09-d6e1-4d1c-aa86-e03349bd9de5 p10:musikone p2:192.168.33.117 p3:2024-07-24T22:00:34.745604018+02:00 p4:0 p5:Tempo [okhttp] p6:false p7:true p8: p9:okhttp]" elapsedTime="44.075µs" error="FOREIGN KEY constraint failed" requestId=MusikONE/JMrCnT9dZZ-000823 rowsAffected=0
Jul 24 22:00:34 MusikONE navidrome[439]: time="2024-07-24T22:00:34+02:00" level=debug msg="API: New request /rest/getStarred2" client=Tempo requestId=MusikONE/JMrCnT9dZZ-000825 username=musikone version=1.15.0
Jul 24 22:00:34 MusikONE navidrome[439]: time="2024-07-24T22:00:34+02:00" level=warning msg="API: Invalid login" auth=subsonic error="data not found" remoteAddr="192.168.33.117:46797" requestId=MusikONE/JMrCnT9dZZ-000825 username=musikone
Jul 24 22:00:34 MusikONE navidrome[439]: time="2024-07-24T22:00:34+02:00" level=info msg="Registering new player" client=Tempo id=b99a3741-c0b8-4046-882f-a926c1d20da7 requestId=MusikONE/JMrCnT9dZZ-000825 type=okhttp username=musikone
**Jul 24 22:00:34** MusikONE navidrome[439]: time="2024-07-24T22:00:34+02:00" level=error msg="SQL: `INSERT INTO player (client,id,ip_address,last_seen,max_bit_rate,name,report_real_path,scrobble_enabled,transcoding_id,user_agent,user_name) VALUES ({:p0},{:p1},{:p2},{:p3},{:p4},{:p5},{:p6},{:p7},{:p8},{:p9},{:p10})`" args="map[p0:Tempo p1:b99a3741-c0b8-4046-882f-a926c1d20da7 p10:musikone p2:192.168.33.117 p3:2024-07-24T22:00:34.746988823+02:00 p4:0 p5:Tempo [okhttp] p6:false p7:true p8: p9:okhttp]" elapsedTime="51.609µs" error="FOREIGN KEY constraint failed" requestId=MusikONE/JMrCnT9dZZ-000825 rowsAffected=0

Note that even if the smartphone with Android 9 connects and plays the audio tracks correctly the log has errors.

Thanks for your support
BR
PT

**Comment by ptartari** [comment]
Hello everyone!
I just tested the client installed on my two devices with Navidrome demo server [https://demo.navidrome.org] and it works without issues, so the issue is in my server installation, but at the moment I don't know, for now how to solve it.
I will investigate further.
Any help is welcome.
Thanks
BR
PT
