### ISSUE TITLE
Play pause

### ISSUE THREAD

**Issue by ps8303383** [CappielloAntonio/tempo#224]
style="@style/PlayerControlButtonBaseStyle.PlayButton
style="@style/PlayerControlButtonBaseStyle.PauseButton
above code is working on exoplayer2 what new code on play pause exoplayer media3

**Comment by CappielloAntonio** [comment]
`style="@style/ExoStyledControls.Button.Center.PlayPause"`

You can take a look at the [layout ](https://github.com/CappielloAntonio/tempo/blob/main/app/src/main/res/layout/inner_fragment_player_controller_layout.xml)of the music player.
