### ISSUE TITLE
[Feature request] Support adding songs as favorites while offline

### ISSUE THREAD

**Issue by ThePBone** [CappielloAntonio/tempo#23]
Hi, thanks for building this awesome project!

It would be great to be able to add new songs as favorites even while offline. 
The app could temporarily store the new favorites in a backlog and sync them to the server once the internet connection has been restored, similar to DSub. This would be useful for trips to remote places with bad or no mobile reception.
At the moment, attempting to do this results in the favorite button resetting to whatever state it was before.

**Comment by CappielloAntonio** [comment]
I released a new version in pre-release, if you like you can test it.

**Comment by CappielloAntonio** [comment]
I'll close this issue now. 
Feel free to reopen it if needed.
