### ISSUE TITLE
[Feature Request] - Radio discovery through Radio Browser 

### ISSUE THREAD

**Issue by adrienneteicher** [CappielloAntonio/tempo#234]
## Summary
Allow users to search radio streams using Radio Browser search engine 

## Use Case
Its a lot easier than manually adding streams

## Additional context
https://www.radio-browser.info/

**Comment by CappielloAntonio** [comment]
Sorry, Tempo was designed as a companion app for Subsonic servers. 
At the moment I have no plans to add additional features by integrating other services, but if I ever change my mind, I will inquire about this service.
