### ISSUE TITLE
[Feature Request] - Autoscroll synced lyrics

### ISSUE THREAD

**Issue by MRodneyMcKay** [CappielloAntonio/tempo#239]
## Summary
On the lyrics pane, it would be nice of the lyrics would be synced to the music.

## Description
From synced lyrics tag, the player would show/highlight/scroll to the relevant section of the lyrics.

## Use Case
We would see what is being sung at the moment.

## Additional context
Spotify and symphonium has this feature

**Comment by Benjiiben53** [comment]
Isn't sync lyrics already available ?

For me it's already available.

**Comment by MRodneyMcKay** [comment]
For me, it doesn't scroll automatically

**Comment by CappielloAntonio** [comment]
The fundamental prerequisites for the song lyrics to be shown in sync are:
- the song must have lyrics with timestamps adjusted correctly
- Server must support this feature

Below is a short video in a situation that meets both requirements.


https://github.com/CappielloAntonio/tempo/assets/14802539/0cb34a16-59f6-4bef-94ce-3553925aedef
