### ISSUE TITLE
[Feature Request] - Allow persistent ignore for offline use

### ISSUE THREAD

**Issue by SatanicMechanic** [CappielloAntonio/tempo#240]
## Summary
Using tempo when disconnected from my LAN causes a 'server unavailable' message at every launch, which is a minor annoyance.

## Description
Allow for disabling of the message on a timed or permanent basis.

## Use Case
I use tempo to play downloaded music while away from home.  Scrobbling to last.fm is a bit flaky, but it otherwise works great. I just don't want the repeated server offline message.

## Additional context
Related to https://github.com/CappielloAntonio/tempo/issues/132

**Comment by CappielloAntonio** [comment]
Hi @SatanicMechanic,
are you referring to this screen? The dialog does not recur for the next hour when the "Continue anyway" button is pressed. If this is not the case or if you think the functionality should be changed, reopen this issue.

![Screenshot_20240525-224230_Tempo](https://github.com/CappielloAntonio/tempo/assets/14802539/140388b1-9d51-4a7e-bfde-307b1fed4861)
