### ISSUE TITLE
[Feature Request] - Jellyfin support

### ISSUE THREAD

**Issue by vfosnar** [CappielloAntonio/tempo#241]
## Summary
Support Jellyfin as a source server like [feishin](https://github.com/jeffvli/feishin) does.

## Additional context
I have recently migrated to Jellyfin to centrally manage all my media, there is no good app for streaming music that can both store music offline and show recommendations.

**Comment by CappielloAntonio** [comment]
Sorry, but Tempo will remain exclusive to Subsonic servers for now. I must also add that the recommendations you see in the app were created using the APIs made available by the server, so if this fundamental requirement were to be dropped, they would not be there.
However, I don't rule out retracing my steps in the future, as Tempo was initially created specifically for Jellyfin.
