### ISSUE TITLE
[Feature Request] - Support disc titles

### ISSUE THREAD

**Issue by Hydronicx** [CappielloAntonio/tempo#243]
## Summary
Add a line before each disc with the disc's title.
If the discsubtitle tag is not present, simply show "DISC 1", "DISC 2", etc.
If the discsubtitle tag is present with value X on disc number N, show "DISC N: X".

## Description
All in the summary.

## Use Case
This is very easy to implement and very important to album collectors who use the discsubtitle tag as some multi-disc albums name the discs in a meaningful way.
For example, think of a two-disc deluxe edition of an album by a band, where the first disc is the album proper and the second disc is a live recording somewhere. In this case, the first disc might be titled with the album's name whereas the second disc might give details on the date of the live recording and the place, etc.

## Additional context
Right now there is no disc information displayed in the UI. The discs are simply separated by a line in the tracklist.

**Comment by CappielloAntonio** [comment]
I currently don't have any albums with the discsubtitle tag, so I can't fully test my implementation. However, Opensubsonic is bringing this new information into the API, and if the information arrives, I will display it in the interface.

![Screenshot_20240525-202304_Tempo](https://github.com/CappielloAntonio/tempo/assets/14802539/66b94448-4323-48dd-8480-fff968ebde22)

**Comment by CappielloAntonio** [comment]
I'll give you a test apk so you can test it out:
[app-notquitemy-debug.zip](https://github.com/CappielloAntonio/tempo/files/15445009/app-notquitemy-debug.zip)

**Comment by Hydronicx** [comment]
Thanks for implementing this so quickly. I see some interesting behavior on the app.

From Home -> Search bar -> Album, the disc subtitles show up. However, the disc numbers are not maintained. Ideally, both the disc numbers and the titles should be displayed, separated by a separator of your choice (colon or dash). For example: "Disc 1: Mixed" or "Disc 1 – Mixed".

![Screenshot_20240529-101235~2](https://github.com/CappielloAntonio/tempo/assets/16652450/f27f6d0f-8077-4272-9614-2e5d45c36ac0)

From Library -> Browse albums -> Search bar -> Album, the disc subtitles don't show up. Here below a screenshot for the same album:

![Screenshot_20240529-101305~2](https://github.com/CappielloAntonio/tempo/assets/16652450/9c1c04f6-8300-4b18-9997-a0957a798fcb)

**Comment by Hydronicx** [comment]
@CappielloAntonio in case you didn't see it

**Comment by CappielloAntonio** [comment]
I fixed the issue, thanks for noticing!

[app-notquitemy-debug.zip](https://github.com/user-attachments/files/15526445/app-notquitemy-debug.zip)
