### ISSUE TITLE
[Feature Request] - Support albums with different release date and original year

### ISSUE THREAD

**Issue by Hydronicx** [CappielloAntonio/tempo#247]
## Summary
Reissued albums can have two tags: one for the original year (for example 2002) and one for the release date of the reissue (for example a 20th anniversary edition in 2022). It would be nice to show both pieces of information somehow in the UI.

## Description
As of now, I think only the original year is displayed.

## Use Case
This would be very useful for those who have different versions of one album.

## Additional context
Here is a screenshot for the expanded edition of The Eminem Show, which only shows the original year of 2002, not the release date of 2022:

![Screenshot_20240529-101808](https://github.com/CappielloAntonio/tempo/assets/16652450/b10aa9cf-64bd-46ee-bfad-e6cb894ee57f)

**Comment by CappielloAntonio** [comment]
I've added release date and original release date to album notes, if available.
The release date is not always available, and especially it is not available with older versions of the Subsonic API (once again we thank the enormous work behind the OpenSubsonicApi project).

![Screenshot_20240602-201946_Tempo](https://github.com/CappielloAntonio/tempo/assets/14802539/8a189c25-962f-45d0-acce-4a4c08040479)

**Comment by ahmadelf** [comment]
Nice. Only thing I noticed is there seems to be a bug with the original release date. For a release date of 2020 (no day or month in tag), it displays "originally December 31, 2019". This happens on several releases.

Also, soon it seems like there will be a new tag in Navidrome (MusicBrainz Album Comment) used to distinguish between different versions of the same album (e.g. deluxe edition, remastered, reissued, etc.). Just mentioning this in anticipation because it's related to this.

**Comment by Hydronicx** [comment]
Nice. Only thing I noticed is there seems to be a bug with the original release date. For a release date of 2020 (no day or month in tag), it displays "originally December 31, 2019". This happens on several releases.

Also, soon it seems like there will be a new tag in Navidrome (MusicBrainz Album Comment) used to distinguish between different versions of the same album (e.g. deluxe edition, remastered, reissued, etc.). Just mentioning this in anticipation because it's related to this.

**Comment by CappielloAntonio** [comment]
Yes, I noticed it too. But I don't think it's a bug, or rather, it's not a malfunction. The information was passed to Tempo from Navidrome, so the problem would be found there or even in the data source used by Navidrome.
