### ISSUE TITLE
Favouriting a song in the dot menu of songlist doesn't work

### ISSUE THREAD

**Issue by dnno** [CappielloAntonio/tempo#25]
When you open the dot menu of a song in the song list, there's an option to favourite that song. This, however, currently doesn't work. There's no obvious error showing, just nothing happens.

![IMG_20230802_111308](https://github.com/CappielloAntonio/tempo/assets/2003552/011045bd-44e8-4d3c-97b7-152f65ae8eea)

**Comment by CappielloAntonio** [comment]
Coincidentally just these days I worked on a major refactor of the API of the favorites.
I'm about to release a pre-release version of the app to test these changes.
Try it and tell me what you think: the problem should be fixed (hopefully I haven't introduced any other bugs).

**Comment by CappielloAntonio** [comment]
I have released a new pre-release version, you can try it if you want and tell me if the problem is solved.

**Comment by CappielloAntonio** [comment]
You know what? Maybe you're right. 
I'm going to change the current behavior so that it doesn't automatically close on click. 
I'll test a bit before I release it.

I'll close this issue now, thanks for your support!

**Comment by dnno** [comment]
Thank you so much. I think another coffee is in order! 😀
