### ISSUE TITLE
[BUG] - Placement of the buttons is wrong in the "Edit playlist" menu for some languages

### ISSUE THREAD

**Issue by rkowalsk** [CappielloAntonio/tempo#250]
## Describe the bug
In the "Edit playlist" menu, when the language is set to French or German, the buttons are arranged vertically and scrollable instead of horizontally and well placed.

## Expected behavior
See screenshots.

## To Reproduce
1. Set your language to French or German
2. Go to "Library"
3. Scroll down to the "Playlists" section
4. Press the three dots of a playlist to edit it

## Environment
 - Android device: Fairphone 4
 - Android OS version: /e/os 2.0 (Android 12)
 - App version: 3.8.1

## Logs or Screenshots
How it looks like:

![Screenshot_20240606-205320_Tempo](https://github.com/CappielloAntonio/tempo/assets/43633272/592f409d-cdbe-4907-9db3-1106f4f98561)

How it should look like

![Screenshot_20240606-204954_Tempo](https://github.com/CappielloAntonio/tempo/assets/43633272/d182719f-b30a-49dc-9813-62d270723c1b)

**Comment by dnno** [comment]
I'll see that I find shorter translations for German, at least
