### ISSUE TITLE
Album Overview for Downloaded music

### ISSUE THREAD

**Issue by fabsmusicjunkie** [CappielloAntonio/tempo#26]
I hear a lot music by album and therefore would like to have an album overview of downloaded albums. Would be great to have something like this here.

**Comment by karlprieb** [comment]
That would be great!
Having a downloaded albums overview or even an offline mode where the app works normally but filtering only the downloaded library

**Comment by CappielloAntonio** [comment]
I implemented a first stable version of the thing and it took me longer than I first thought (much longer).

You can now view your downloads grouped by album, artist, genre and year. Not sure about leaving these last two groupings, we'll see.

![-2147483648_-210403](https://github.com/CappielloAntonio/tempo/assets/14802539/ab17dc3b-ed9d-46de-97ea-90c2ac5fdf3c)

**Comment by dnno** [comment]
What is your feeling about having the default filter configured in the settings? Or having the app remember the last selected filter value?

**Comment by CappielloAntonio** [comment]
Yep, I think you're right, it would make sense to have the latest set filter as the default grouping. Implemented!
