### ISSUE TITLE
[Feature Request] - Add Search in Playlist /  Sort in Playlist

### ISSUE THREAD

**Issue by MarmotioTM** [CappielloAntonio/tempo#260]
Hello

Can you please add a search function within playlists?
Also within any playlist we should be able to sort the list by 'date added' and other sorting systems.

Ur work is appreciated, nice app otherwise

Cheers
Marmo

**Comment by MarmotioTM** [comment]
Sort by "Titlenumber" also would fix all my issues i would have with this great app

**Comment by CappielloAntonio** [comment]
While a search functionality within the playlist makes sense and I implemented it with the latest commit, sorting by add data is unfeasible, as I just lack that information (subsonic APIs don't provide it to me)
