### ISSUE TITLE
[BUG] - Titles with HTML tags don't show up correctly

### ISSUE THREAD

**Issue by TacoCake** [CappielloAntonio/tempo#273]
## Describe the bug

I have a song from the band `Motionless in white` titled `</c0de>`. The title is blank in the app. I suppose this is a string sanitation issue.

## Expected behavior

I want the title to show up as `<\c0de>`.

## To Reproduce

1. Have a song with the following name: `<\c0de>`
## Environment
 - Android device: Pixel 8 Pro
 - Android OS version: 14
 - App version: 3.8.1

## Logs or Screenshots

![Screenshot_20240720-131034](https://github.com/user-attachments/assets/be5b367d-204f-42bc-921a-84b719b6d535)
![Screenshot_20240720-131022](https://github.com/user-attachments/assets/5ac3f5f2-69a9-4889-89ee-187721305cb5)
![Screenshot_20240720-131015](https://github.com/user-attachments/assets/7b47f02b-9246-404c-87a3-6bf4c53120ae)
![Screenshot_20240720-131555](https://github.com/user-attachments/assets/2ce13f76-e11e-4301-a8a2-307520f06ff6)

## Additional context
I'm using the Fdroid version, don't know if that's relevant.

**Comment by faelif** [comment]
I can confirm I get the same issue with the album `<Dall>` by `ARTMS`

**Comment by CappielloAntonio** [comment]
Problem already found and fixed, will be corrected for everyone with the upcoming release
