### ISSUE TITLE
[Feature Request] Android TV Version

### ISSUE THREAD

**Issue by Toniob** [CappielloAntonio/tempo#276]
Hi,

I really like the player on my smartphone. Android TV really lacks a good Subsonic client. Do you think you could make a version with an interface for a tv screen ?

Thanks for all the work

**Comment by HamonTeacher** [comment]
I agree.

**Comment by CappielloAntonio** [comment]
I'm sorry, but developing a new app completely from scratch for Android TV would be a significant expense in terms of time and effort that I don't think I can afford at the moment.

**Comment by Toniob** [comment]
I understand. Thanks anyway for you awesome work.
