### ISSUE TITLE
[BUG] - how do I change servers?

### ISSUE THREAD

**Issue by eddyizm** [CappielloAntonio/tempo#287]
## Describe the bug
seems like I am missing something. Happy to PR some how to docs in the git hub page. 

## Environment
 - Android device: [Device Model]
 - Android OS version: [Android Version]
 - App version: [App Version]
 - Other relevant details: [e.g., specific network conditions, external dependencies]

**Comment by senna1992** [comment]
It's a translation bug.
If you press "logout" you are taken to the page where servers can be added / switched

**Comment by eddyizm** [comment]
@senna1992 Thanks, I actually ended up figuring it out but I couldn't remember how to do it as I had once set up a couple of servers and generally didn't switch much. 

Although not the most intuitive, it seems like it loses my password settings when I switch. Is that intended or something that should be filed as a bug?

**Comment by CappielloAntonio** [comment]
The password must be entered again only if you modify an already existing server. If you use a previously created server, the password remains the same and does not need to be entered.
