### ISSUE TITLE
[Feature Request] - Enable album sort by most played, recently played, etc.

### ISSUE THREAD

**Issue by brian-doherty** [CappielloAntonio/tempo#288]
## Summary
It would be nice to enable album sort by the sort options available on the server, like most played or recently played.

## Description
Right now, the app is pulling the full album list and sorting locally. That precludes any sorting based on attributes not included in the <album> element. I'm proposing to change the album catalog view to fetch the list fresh when a new sort is used, in order to allow for these.

## Use Case
It's nice to be able to quickly fetch albums I like to listen to a lot, or have listened to recently.

**Comment by CappielloAntonio** [comment]
In the catalog list you can now sort by recently played, most played and recently added albums, with the help of the new OpenSubsonic API and without requesting albums from the server.

![Screenshot_20241120-224944_Tempo](https://github.com/user-attachments/assets/5ddb089e-2f96-4523-8ff5-3b9d44a0e798)
