### ISSUE TITLE
[Feature Request] - Add the option to download all tracks

### ISSUE THREAD

**Issue by jamie6king** [CappielloAntonio/tempo#293]
## Summary
Add an option in settings to download all tracks that are available.

## Description
Add an option (probably with a warning) to download all the tracks on to the device in order to save data while out. Currently you can download specific songs / albums, but this can get annoying if you have a lot.

Maybe add a warning that this will use a lot of storage space?

## Use Case
Allows full offline playback, which is rare for a Subsonic / Navidrome client.

**Comment by haitispaceagency** [comment]
> ## Summary
> Add an option in settings to download all tracks that are available.
> 
> ## Description
> Add an option (probably with a warning) to download all the tracks on to the device in order to save data while out. Currently you can download specific songs / albums, but this can get annoying if you have a lot.
> 
> Maybe add a warning that this will use a lot of storage space?
> 
> ## Use Case
> Allows full offline playback, which is rare for a Subsonic / Navidrome client.
> 
> ## Additional context
> 

have you found an app that let's you do this? I'm coming from iOS using amperfy and have become spoiled by it. I'm literally dragging around my deactivated iphone just to have my music local. my home upload speed is not good enough to stream my music 😢
