### ISSUE TITLE
[Feature Request] - Navidrome/Tempo - Biography Artist with MusicBrainz and Radio feature on ListenBrainz

### ISSUE THREAD

**Issue by black00019** [CappielloAntonio/tempo#297]
## Summary
Biography Artist with MusicBrainz and Radio feature on ListenBrainz in Navidrome instance controlled by Tempo

## Description
I wish I had the artist bio taken from MusicBrainz instead of last.fm.

## Use Case
The "Radio" function seems to only work with a Last.fm API Key, it would be nice to work with ListenBrainz too.
The function is important as it promotes a free and community-managed service, however last.fm is closed.

## Additional context
![Screenshot_20241015-113346 1](https://github.com/user-attachments/assets/fddac3f2-7116-4581-985d-b555b80d040e)

**Comment by CappielloAntonio** [comment]
The information displayed on the screen comes from the Subsonic API used. I have no power over the source of the information. Tempo does not make any direct calls to Last.FM, ListenBrainz or MusicBrainz. I only communicate with the server (in your case Navidrome)
