### ISSUE TITLE
Battery optimizations

### ISSUE THREAD

**Issue by Mihara** [CappielloAntonio/tempo#3]
On Oneplus 9 Pro, Android 12, every time I start or switch to Tempo, a pop-up asks me to disable battery optimizations. But then it takes me to a list of applications which does not include Tempo.

Manually disabling battery optimizations where it actually should be done does not stop this.

**Comment by ivan-avalos** [comment]
You need to select “All apps” in the dropdown menu, so that you get Tempo in the list. It was confusing for me too, but I figured out after three Tempo optimization popups.

**Comment by ivan-avalos** [comment]
Btw, Pseudosonic is awesome!

**Comment by CappielloAntonio** [comment]
Yeah, sorry about that. I have to somehow ask the user to remove the "optimizations" of the Android manufacturers to avoid strange behavior of the app. I also can't do this job for the user, but can only walk the user to the exact section of the settings. But we agree that the message appears too many times.

**Comment by Mihara** [comment]
OnePlus 9 Pro on Android 12 simply doesn't have a dropdown for me to select "All apps" from. But the real issue is that I did disable the optimizations, but it keeps popping up, which probably means that it is not being tested for in a platform-Independent way.

**Comment by CappielloAntonio** [comment]
It's a tricky business to control the optimization on non-AOSP devices (or ones that don't keep a faithful line to what Google intended). Xiaomi, OnePlus, Huawei, Realme, who more and who less manages the optimization of apps in their own way. For now I'm waving the white flag, but at least I'll stop begging to remove the app optimization. Now you can choose "Don't ask again" and the dialog will no longer appear.

**Comment by Mihara** [comment]
Sending users to read https://dontkillmyapp.com/ instead might be an option?

**Comment by CappielloAntonio** [comment]
I was also thinking about it. It's not a definitive solution, much less my favorite one, but it's still an indication for the user. I've just uploaded a new version with a lot of fixes, and among them I've also changed the way the battery optimization dialog is displayed.

**Comment by CappielloAntonio** [comment]
I'm going to close the issue, in case of problems or other suggestions feel free to reopen it.
