### ISSUE TITLE
[Feature Request] - FireTV Compatibility

### ISSUE THREAD

**Issue by marc5477** [CappielloAntonio/tempo#310]
## Summary
First, thank you for this wonderful app. I love it on my phone and I would love it even more if it worked with Android TV devices. I can install it on my FireTV and it does work but there are two issues and hopefully they are not very hard to fix. When fixed, it should allow Tempo to work well on a Android TV device. 

## Description
First navigation indicators arent always present. For instance, if I want to select one of the decades, its hard because there is no highlighting nor any sort of selection indicators or pointing arrow to know what it is I am selecting.

Second, screen isnt rendered fully on the vertical axis. Horizontally it seems ok and can scroll, but vertically it seems to cut off before reaching the bottom. For example, if you select a playlist, you cannot see the controls at the bottom.

## Use Case
Im using it on a FireTV stick on a 1080p TV. Havent tried it at 4k yet.

**Comment by CappielloAntonio** [comment]
Hi, it's not a priority for me at the moment because I don't even have a test device and it would be difficult for me to develop. Any help, from pull requests to donations, is welcome.
