### ISSUE TITLE
[Feature Request] - Jump to album from song

### ISSUE THREAD

**Issue by SemvdH** [CappielloAntonio/tempo#314]
## Summary
I would love to have the option to jump to the album from a song

## Description
A lot of times I'll be playing a song and want to see the oher songs on the album. When I click the album art while in the "now playing" screen, there are 4 options, but none of them are to go to the album directly. Also, when clicking on the little "i" to get the song info at the top of the screen, I would expect that tapping the album name could take me to the album

## Use Case
When you're listening to a song and want to see the other songs on that album

## Additional context

Given that the 4 options when tapping the album art of a song already fill the available space, it would be best (UI-wise) in my opinion to add the functionality of going to the album to the "album" entry when pressing the "more information" button (i) on a song

**Comment by CappielloAntonio** [comment]
Hi, you can click on the song title to open the album page

**Comment by rumpeltux** [comment]
Great that this works! But tbh this is a bit unintuitive (I had to come here to learn this).
