### ISSUE TITLE
[Feature Request] - make downloaded tracks visible to other music players

### ISSUE THREAD

**Issue by Sohalt** [CappielloAntonio/tempo#315]
## Summary
I would like to be able to play downloaded songs with other music players.

## Description
When songs are downloaded they should be available through the android media api or on the filesystem (with directories/files named after artist>album>track).

## Use Case
I don't like the Tempo playlist UX and this would allow me to use another app to create playlists. I'm sure there are other features that tempo doesn't have at the moment that would be solvable like this by using another app. It also allows to share the audio files (eg mp3s or flacs) through the regular Android file sharing options (to send it via eg email, chat, syncthing, etc).

**Comment by CappielloAntonio** [comment]
Hi, the songs are downloaded using the media3 library caching feature which does not provide the original file as it is on the server. I do not currently plan to actually download the file as it would require a major rewrite of the feature, but any help is welcome.
