### ISSUE TITLE
Download at the server's folder level 

### ISSUE THREAD

**Issue by molohov** [CappielloAntonio/tempo#34]
Currently only albums and tracks can be downloaded. I wonder if all the files in a folder, at the server level, could be downloaded?

**Comment by CappielloAntonio** [comment]
For Subsonic's API I have no way of knowing what files are inside a folder (recursively), so we have to get creative if we want to achieve this.

The simplest and most viable solution would be to download all the files within the folder that the user is currently seeing. This way I avoid blindly downloading files.

The worst solution, which I have no intention of pursuing, would be to recursively go down one level in the folder tree and download every single file there. This would mean that the user doesn't know what and how much he is downloading and, even worse, I would have to make an unspecified number of calls to the server to rebuild the directory tree and then download the files.

So I guess I'll go the first way.

**Comment by CappielloAntonio** [comment]
Feature implemented with my last commit.

**Comment by molohov** [comment]
Thanks for entertaining the idea and implementing so quickly!

**Comment by CappielloAntonio** [comment]
Not at all, it's a feature that makes sense to have implemented.
