### ISSUE TITLE
[Feature Request] Material You

### ISSUE THREAD

**Issue by AAGaming00** [CappielloAntonio/tempo#37]
Pretty much the title, material you theming support would be appreciated.

Also, what if it could be synchronized with the album art colors as an option perhaps?

**Comment by AAGaming00** [comment]
On my phone it has a darker purple ish background while my material you theme isn't. weird.

**Comment by CappielloAntonio** [comment]
It seems like it's not working as it should.  Such an obvious thing yet... Thanks for pointing it out!

**Comment by CappielloAntonio** [comment]
Bug introduced after inserting the Splash Screen and I never realized. Something so obvious but it seemed to work as it should.

Anyway, thanks to one of the long-standing [material-component](https://github.com/material-components/material-components-android/issues/2555) bugs that is still not fixed.

I solved the problem, thanks again. The fix will be released with the next app release.
