### ISSUE TITLE
java.lang.IllegalStateException

### ISSUE THREAD

**Issue by ivan-avalos** [CappielloAntonio/tempo#4]
Ever since I started self-hosting my music with Subsonic a few years ago, I've been longing for a new modern-looking and fully-functional Subsonic client for Android. This might be it! However, it's not working for me. The Home section is empty, and the library section is able to show a list of folders and albums, but not the albums themselves. Whenever I click “Scan library,” it throws this error:

```
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was NUMBER at line 1 column 40 path $.subsonic-response.error.code
```

I'm using Supysonic 0.7.2, which targets Subsonic API version 0.12.0, so I need to enable the low-security mode to use plain-text passwords (at least that's what my intuition tells me the mode is for).

**Comment by ivan-avalos** [comment]
The URL of my server is not in a subdirectory! In case that's important. It goes something like: `https://example.com`.

**Comment by CappielloAntonio** [comment]
Hi Ivan, could I bother you to fix this bug? 
I made some changes to the code and uploaded a new version of the app in the release section. 
Could you please try it and report if the app behaves the same or has something changed?

**Comment by ivan-avalos** [comment]
Thanks! It was fixed! :D
