### ISSUE TITLE
Screen Rotation

### ISSUE THREAD

**Issue by c0utta** [CappielloAntonio/tempo#40]
Hi Antonio,

A really minor bug.  An artifact is left behind when rotating portrait/landscape/portrait.

Screenshot attached:

<img src="https://github.com/CappielloAntonio/tempo/assets/117241076/12310ea6-3f4b-4313-b789-d451e6343d24" width=25% height=25%>

**Comment by CappielloAntonio** [comment]
Thank you for your reporting!

Now I manually collapse bottomSheet on device state change.
