### ISSUE TITLE
Cannot play a track with an index higher than 16

### ISSUE THREAD

**Issue by Elbullazul** [CappielloAntonio/tempo#43]
When selecting a song in a playlist or a playlist with an index higher than 16 (ex. the 18th song in a playlist), Tempo plays the 16th track instead.

**Comment by dnno** [comment]
The culprit is a constant used in `MusicUtil.getPlayableMediaPosition()`

`const val PRE_PLAYABLE_MEDIA = 15`

**Comment by CappielloAntonio** [comment]
I'm working on it
