### ISSUE TITLE
Some Problems with playlists

### ISSUE THREAD

**Issue by dnno** [CappielloAntonio/tempo#46]
I discovered some problems with playlists:

- When you delete a playlist in Tempo, it is remotely deleted but not removed from the app UI. 
- New playlists created on the server only show up once the app is restarted (same problem as above really)
- Clicking the dot menu of an empty playlist crashes the Tempo
- Renaming a playlist doesn't work. In fact it deletes the playlist.

For issues 1 and 2 The UI needs to be refreshable, I think. Refreshing should happen automatically after playlist deletion or should be manually triggerable (pull down to reload?) by the user.

**Comment by CappielloAntonio** [comment]
Hey @dnno thanks for reporting!
I fixed the playlists issues, you can see the code and test if all the issues are now fixed.

**Comment by dnno** [comment]
There's a remaining NPE, I opened a PR, see #47

**Comment by CappielloAntonio** [comment]
Yes, I fixed that problem as well.
I did it a priori, even before giving the adapter class the result of the server call:

```
playlistEditorViewModel.getPlaylistSongLiveList().observe(requireActivity(), songs -> {
    if (songs != null) {
        playlistDialogSongHorizontalAdapter.setItems(songs);
    }
});
```

In this way, inside the adapter, the list will never be null, at most empty.

**Comment by CappielloAntonio** [comment]
This is the commit mentioned above https://github.com/CappielloAntonio/tempo/commit/1eda7cef9ee8c0e1d154a28c2d4334c5b60220c4

**Comment by dnno** [comment]
Oh, I'm sorry, my fork sync missed that commit, it seems. bad timing...

**Comment by CappielloAntonio** [comment]
No, don't apologize, it was me who pushed online waiting a few minutes between one commit and another
