### ISSUE TITLE
Dot menu is too small

### ISSUE THREAD

**Issue by dnno** [CappielloAntonio/tempo#48]
Oftentimes when I want to click on the dot menu of a song, I accidentally click on the song itself triggering playback. I think it would be a good idea to increase the clickable area of the dot-menu to make this easier to work with.

**Comment by CappielloAntonio** [comment]
It's a problem that certainly needs to be fixed, but I would like to take the opportunity to remind you that often a long tap will have the same effect as the three dots click

**Comment by dnno** [comment]
Oh nice, I missed that! Thanks for the hint!

**Comment by CappielloAntonio** [comment]
Hi @dnno, I finally found the time to adjust the size of the dot buttons. If you find any other hard-to-click buttons, tell me and I'll make them bigger.

**Comment by dnno** [comment]
Thanks!
