### ISSUE TITLE
Request - Album artwork in Notification player

### ISSUE THREAD

**Issue by cirdanlunae** [CappielloAntonio/tempo#49]
Having the artwork appear in the player in the Notification area would be a great addition for aesthetics. 

This is the current behavior
![Screenshot_20230828-001044](https://github.com/CappielloAntonio/tempo/assets/5956790/03617cfb-ac1b-4925-934b-887793d5b994)

This is the expected behavior (dSub, for example, does this, along with many "Major" streaming platforms)
![Screenshot_20230828-001428](https://github.com/CappielloAntonio/tempo/assets/5956790/19d3864f-ea58-4be2-bf62-47e0d3d764ed)

**Comment by CappielloAntonio** [comment]
Hi @cirdanlunae, the cover art should be there. This is a video I made yesterday for another user, as you can see from the last few seconds of the video, the cover is where it should be.


https://github.com/CappielloAntonio/tempo/assets/14802539/95061a5d-1627-46bb-bce8-c030188d6b78

Could you please tell me which server you are using? Or if it's an offline track? Your situation usually occurs when the server is unreachable and therefore the cover art is not available.

**Comment by sibwaf** [comment]
Yup, also not working for me.

Server: gonic
Android: 13 (Samsung's OneUI)
Tempo: 3.5.3 (the latest one)

## Tempo
![image](https://github.com/CappielloAntonio/tempo/assets/7131069/79d5afef-264d-43ec-b784-5ffc145f27aa)

## Subtracks
![image](https://github.com/CappielloAntonio/tempo/assets/7131069/8541ade8-7ea6-4226-adab-446a397bc8ce)

**Comment by CappielloAntonio** [comment]
Hi guys, may I ask you to try this test apk? 
It almost seems that the AOSP version of Android "knows" where to get the file artwork, while for all the others it must be specified.

[app-notquitemy-debug.zip](https://github.com/CappielloAntonio/tempo/files/12452621/app-notquitemy-debug.zip)

**Comment by sibwaf** [comment]
Seems to be working only for files with embedded cover art. For albums that have the cover image as a separate file - same as before, displayed in the app, but not in the notification.

**Comment by CappielloAntonio** [comment]
Yes, sorry, I may have mistaken the id to use. 
Would you try this new release?

[app-notquitemy-debug.zip](https://github.com/CappielloAntonio/tempo/files/12453271/app-notquitemy-debug.zip)

**Comment by sibwaf** [comment]
Yep, seems to be working fine now. Thanks!

**Comment by CappielloAntonio** [comment]
Thanks to you! 
I'm closing this issue, but if you have any problems, please feel free to reopen it.

**Comment by cirdanlunae** [comment]
Wow, I go to bed putting in the bug report, and I wake up to it fixed! Amazing--thank you!!!

That APK did the trick. My server/phone info just in case it's useful in case 

Navidrome 0.49.3
Phone is running CalyxOS (up to date)
Most recent Tempo apk

**Comment by CappielloAntonio** [comment]
I just wanted to point out that this apk has a different signature from the one released for all as it is the one intended for F-Droid. I'll be releasing a new release of the usual version soon, so you don't have two apps installed at the same time.
