### ISSUE TITLE
Downloading indicator

### ISSUE THREAD

**Issue by ivan-avalos** [CappielloAntonio/tempo#5]
Hey! The download feature seems to be working fine, however, there's no indicator to let me know if a song is downloaded or is being downloaded. Tracks simply appear in the downloads section and in the notification shade after they're downloaded. I think it would be nice to have download indicators.

**Edit:** There appears to be a “Downloading” progress notification, but still, none of the notifications tell me which song they are downloading (other than the song ID), and when I download a lot of songs, the notification channel quickly fills up with tons of notifications.

**Comment by CappielloAntonio** [comment]
Currently, the download of a track is indicated by its presence in the Download section, by the download notification and by the "download arrow" icon. In the next versions I will try to make the status clearer.

![-2147483648_-210367](https://github.com/CappielloAntonio/tempo/assets/14802539/4166cb42-9869-4ba2-beb9-e5d39e661c7d)

**Comment by CappielloAntonio** [comment]
After more time than I would have liked, I just added the downloaded file title to the download notification.

![-2147483648_-210394](https://github.com/CappielloAntonio/tempo/assets/14802539/8bb21e95-a8ef-4eb5-9dbd-53effed48cba)
