### ISSUE TITLE
Downloading and Download complete notifications are grouped together

### ISSUE THREAD

**Issue by molohov** [CappielloAntonio/tempo#52]
The consequence is that, when downloading items, the user has to wait for all downloads to complete before they can dismiss the Download Complete notifications. It's a very minor annoyance, but wondering if a solution is simple.

**Comment by CappielloAntonio** [comment]
Hi @molohov, unfortunately I don't think I can reproduce the problem. 

As you can see from the video, I can get rid of the download completed notifications, at best it's not possible to get rid of the foreground notification of the entire download, but it's understandable as the download is still in progress.


https://github.com/CappielloAntonio/tempo/assets/14802539/e4e4f0d8-5650-4051-b954-f7ab5ab8ce76

**Comment by molohov** [comment]
Thanks for the video. I didn't describe the problem correctly. In your video, the notifications are all under the Tempo group. I meant that one has to wait for all the downloads to complete before they can swipe the Tempo group itself away (hence, all the notifications related to downloads at once)

**Comment by CappielloAntonio** [comment]
Hey @molohov, @GallowsDove should have fixed the notification issue. I will be releasing a new version of the app soon, could you kindly test it?

**Comment by molohov** [comment]
Yes, now it's working wonderfully! Thanks for the tremendous development, this app only gets better and better!
