### ISSUE TITLE
Browsing by Folder shows all subfolders, not just the subfolders under the main folder

### ISSUE THREAD

**Issue by cirdanlunae** [CappielloAntonio/tempo#53]
Not sure how to explain it. Let's say I have these Folders in my Subsonic setup:

Jazz
-John Coltrane
-Miles Davis

Classical
-Beethoven
-Mozart

When clicking "Classical" to browse by folder in Tempo, I should see only Mozart and Beethoven. However, I see:
-Beethoven
-John Coltrane
-Miles Davis
-Mozart

Same things happens when browsing by folder for "Jazz"

Other Subsonic compatible apps handle it fine.

Information: 
-Tempo: 3.5.3
-OS: CalyxOS 4.12.0 (Android 13)
-Server: Gonic 0.15.2

**Comment by CappielloAntonio** [comment]
I ran into this bug trying to fix another big one showing up with Airsonic Advanced. Would you like to test whether your problem is solved?

[app-notquitemy-debug.zip](https://github.com/CappielloAntonio/tempo/files/12487096/app-notquitemy-debug.zip)

**Comment by cirdanlunae** [comment]
Yep, that fixed it! Greatly appreciate your assistance!
