### ISSUE TITLE
"Remove all" flashes for a moment before being removed again when opening album bottom sheet

### ISSUE THREAD

**Issue by GallowsDove** [CappielloAntonio/tempo#62]
On albums which have no downloaded songs, which should not have the option to remove all, the option flickers and quickly disappears when you open the bottom sheet.

Expected behavior:
It should be removed before the bottom sheet becomes visible to the user.

**Comment by CappielloAntonio** [comment]
Unfortunately the waiting times are physiological, as I have to wait for the server to return the list of tracks belonging to the album and then I have to check them one by one to see which have been downloaded.

But you're right, the bottom sheet opening seemed to lag. At this point we try to make the interface lag as little as possible, by default the remove all option isn't there and only when I've made sure that there is actually something to remove I show it.

I also took the opportunity to clean up that part of the code a bit.
