### ISSUE TITLE
Support for Lyrics Display

### ISSUE THREAD

**Issue by tobsowo** [CappielloAntonio/tempo#63]
The ability to view lyrics of songs played.

**Comment by CappielloAntonio** [comment]
Hi @tobsowo, the ability to see song lyrics is already there as you can see from the video.
Anyway, I'll try to make it more visible.


https://github.com/CappielloAntonio/tempo/assets/14802539/885b8de7-e428-4ceb-8102-d84c9937c9b2

**Comment by tobsowo** [comment]
Thank you.
Didn't know I needed to swipe.
