### ISSUE TITLE
Swipe to Go to Next Track on Now Playing Screen

### ISSUE THREAD

**Issue by t0fr** [CappielloAntonio/tempo#64]
This is more of an enhancement/personal preference.

I'd really like to be able to swipe left/right to go to next/previous track.
I notice you already had swipe left to go to a description. Perhaps change this to swipe down?

If we could have an option in the settings to change the behavior, that would be nice

Otherwise, the app looks pretty slick. Thanks!

**Comment by CappielloAntonio** [comment]
I'm sorry, but I don't think I will add this new gesture. 

In the past the situation was as you described, but I didn't like the performance and the integration with the other gestures. Now a swipe to the right takes you to the lyrics section, while a swipe down to the playback queue.

**Comment by Hayajiro** [comment]
Just stumbled over this while evaluating and testing out options for a self-hosted music stack. The app itself looks really slick, but missing next / previous track gestures  (as well as full-page swipe down to hide the Now Playing screen) are something of a "show-stopper" for me.

Perhaps this could be solved with a settings toggle? That way, we can have both gesture types and people can choose which behavior they prefer. I'd definitely be up to implementing this if such a toggle would be accepted (although I'm definitely not a UI-dev, so it might take me some time :sweat_smile:).
