### ISSUE TITLE
[Feature request] Tap the Now Playing bar to bring it up

### ISSUE THREAD

**Issue by molohov** [CappielloAntonio/tempo#7]
It took me a while to realize that you have to SWIPE it up to make it appear!

**Comment by CappielloAntonio** [comment]
There are so many gestures that I think only I know about at the moment, as I created the app with my needs in mind.
As I wrote to another user:

> I created it based on my needs and based on what I believe to be nice. There are several gestures that should be known: a long tap on the main elements (albums, songs, artists, playlists, podcast channels and episodes, radio stations) opens the bottom sheet menu. The long press on titles activates the section refresh. A swipe up on the lower music player opens the full screen one. From here, a second swipe at the top leads to the what section, while a swipe to the left shows any lyrics of the song. Still on this screen, a tap on the cover shows four actions, while a long tap on the heart opens the dialog for voting for the track. In the queue screen, pressing and holding on a track moves it within the playback queue.

Once perfected I will probably write a new post to inform users or I will try to guide them inside the app.

**Comment by molohov** [comment]
Thanks for the explanation! I would not have figured any of these out :)

**Comment by CappielloAntonio** [comment]
Gestures added! I will test it a bit these days and then I'll release it with the next version of the app.
