### ISSUE TITLE
[Feature Request] listenbrainz.org scrobble and recommendations

### ISSUE THREAD

**Issue by C9Glax** [CappielloAntonio/tempo#72]
This might be a bit larger of a request:
Since you already support last.fm recommendations, I would suggest using the open-source [listenbrainz.org](https://listenbrainz.org) as well.

They have a [well documented](https://listenbrainz.readthedocs.io/en/latest/) API and have a [recommendations endpoint](https://listenbrainz.readthedocs.io/en/latest/users/api/recommendation.html).
What I think might be the biggest challenge, is mapping their `mbid`s to tracks in ones own library to show recommendations.

If I haven't said it yet: I really enjoy this client, the UI is very nice, and development active. With no real alternatives to stream **your own** music this is a promising project. Cheers!

**Comment by CappielloAntonio** [comment]
Hi @C9Glax, it should be noted that any integration occurs firstly via Subsonic APIs and secondly by integrating these into the server. So if Navidrome, for example, supports scrobbling, mixes or the most played tracks from Last.fm or listenbrainz, then Tempo also supports the functionality accordingly.

Tempo does not go beyond the boundaries dictated by Subsonic (and perhaps OpenSubsonic) as it was created as a client for servers that support their APIs.

**Comment by C9Glax** [comment]
Ah okay then I will bug someone elses project ;)
Thanks for the reply
