### ISSUE TITLE
Removing Notification closes Media-Playback

### ISSUE THREAD

**Issue by C9Glax** [CappielloAntonio/tempo#73]
When downloading songs you receive the `Download Completed` Notification.
When swiping right/removing these notification media-playback stops.
The app itself remains open.

**Comment by CappielloAntonio** [comment]
Hi @C9Glax, this is the first time this behavior has been reported and I personally have never encountered it. Could you tell me what version of Android you use? And what is the manufacturer's customization? 

I don't understand why deleting a notification belonging to another channel compared to the music player notification should kill playback.

**Comment by C9Glax** [comment]
Hey there, glad to help.
I have attached two video files showing the behaviour. When there is still ongoing downloads, behaviour is as expected.

https://github.com/CappielloAntonio/tempo/assets/13404778/2462f6d3-645a-4fc3-9e8f-970401162d05

When all downloads are completed, media player is also stopped.

https://github.com/CappielloAntonio/tempo/assets/13404778/72296a53-bad6-48db-9943-2a8018359212

Android Information:

Graphene OS
Google Pixel 6
Version 13
Security 01. Sep 2023
Kernel 5.10.194-android13-4-g290eb1d8e5b9

**Comment by GallowsDove** [comment]
I can replicate the bug on the same hardware/software (GrapheneOS, Pixel 6), I'll look into it further later. Seems to happen only when dismissing at least two grouped notifications. I also believe this might be quite new, since I've never noticed.

**Comment by C9Glax** [comment]
Is it possibly an issue with the OS itself?
I can't think of many media apps that have grouped notifications, so it might just fly under the radar?
Don't know how much work it would be to have a test application to check wether media-player notifications get cleared alongside normal ones...

**Comment by GallowsDove** [comment]
After some more testing, I've noticed that I can replicate the issue in the android emulator within Android Studio, so we can rule out an OS-specific issue. Unfortunately I wasn't able to find the exact cause of the issue

**Comment by GallowsDove** [comment]
Okay, so it appears that implementing #52 would help with this issue as well, as from my testing, dismissing a notification with set groups does not cause the playback to stop

**Comment by CappielloAntonio** [comment]
Hey @C9Glax thanks to the great help of @GallowsDove the problem of removing notifications should have finally been solved. I will be releasing a new version of the app soon, could you kindly test it?

**Comment by C9Glax** [comment]
Sure thing! Will check tomorrow for the new release on here.
