### ISSUE TITLE
[Feature Request] - Show all albums

### ISSUE THREAD

**Issue by GallowsDove** [CappielloAntonio/tempo#83]
**Summary**
Show all for artist's albums

**Description**
Add a show all button for albums in artist's page, which would open a list of albums. 

**Use Case**
The main reason is that there are artists with a lot of albums and the big album covers make it hard to look for a specific one.

**Additional context**
I've had a plan to implement this sooner, just didn't get around to it yet. I can open a PR when I have time

**Comment by CappielloAntonio** [comment]
I have implemented a button for quick layout switching. 
I prefer the horizontal view, but I understand why some might prefer the vertical view. This has been asked before. Anyway, it is now implemented.
