### ISSUE TITLE
[Feature Request] - full controlls in folders

### ISSUE THREAD

**Issue by Cambi0nn** [CappielloAntonio/tempo#86]
## Summary
Add all controlls to add to que etc. to the music folder view.

## Description
Add the following menu:
![c021e9c8-3d9f-4ba6-83bc-d791c945d046](https://github.com/CappielloAntonio/tempo/assets/138434096/2605f1fb-ee3c-48f4-be45-6697209fb18d)
Into the Music Folders tab:
![e8ead086-c75c-441f-a6e4-bae4fa2a752e_1](https://github.com/CappielloAntonio/tempo/assets/138434096/a6bfebf7-680d-4b58-a11a-8ebade467ba4)

So that when you long-press an item in there, the menu comes up (currently it highlights the file but nothing happens). Most perfect would be if this works on audio files and folders alike (where audio file adds the file, and folder adds al files in the folder), but if it just works on audio files that'll be a great start!

## Use Case
One thing I care about in a subsonic app is the ability to browse by the folder structure of my server, as this is the way I organised things. Tempo is one of the few subsonic clients to support this. However, trough folder structure you can only replace the current playlist with all audio files of a folder. This makes it's usage  rather limited.

## Additional context
N/A

**Comment by CappielloAntonio** [comment]
Hi @Cambi0nn the idea can only be implemented in part. I can make the bottomSheet visible only if the selected item is of track type, and therefore I could pop out the songs menu. It is not possible on folders as at the time of the long click I can only know whether the item is of the folder type or not, but not its contents.

**Comment by CappielloAntonio** [comment]
Added menu for tracks in directories.
Test apk:

[app-tempo-debug.zip](https://github.com/CappielloAntonio/tempo/files/12874483/app-tempo-debug.zip)
