### ISSUE TITLE
[BUG] - Unexpected behaviour with downloads

### ISSUE THREAD

**Issue by TH0MVS** [CappielloAntonio/tempo#92]
## Describe the bug
A bug that really confused me !

If you go to the download section and select an album you just downloaded, the following message appear when you click the Info icon on the top right : "The application will only read the original file as provided by the server. The app will explictily request the server for the untroscoded file with the biotyrate of the original source."

If you cut your network, like put your device on airplane mode for example, you won't be able to play your downloaded music. Its like the app try to find the files on the server, not on your device. The app seem to make an immediate copy of the metadatas in the download section, but no immediate synchronization is done with the files you just downloaded.

You need to properly close the app then relaunch it to synchronize your downloaded files (not put the app in the background, really close it). The message change on the Info icon : "The file has been downloaded using the SUbsonic APIs. The codec and bitrate of the file remain unchanged from the source file".

## Expected behavior
A message in the notification should be added at the end of a download, something like : Restart the app to synchronize your downloads. An option in the notification should appear to relaunch properly your app.

## To Reproduce
1. Go to any album
2. Click on the three dots on the top right, select Download all
3. Wait for download to stop, check the notification
4. Go to Download section at the bottom right
5. Select an album you just download
6. Click on the Info icon at the top right, message is "The application will only read the original file..."
7. Put you device on airplane, select any track and try to play it

## Environment
 - Android device: Pixel 6 (GrapheneOS), Redmi Note 10 Pro (ArrowOS)
 - Android OS version: 13 on both
 - App version: 3.5.7 on both
 - Other relevant details: Navidrome 0.49.3

## Logs or Screenshots
N/A, can make some if useful

## Additional context
Great app!

**Comment by GallowsDove** [comment]
I could reproduce this, to summarize the bug:

The app still tries to stream already downloaded tracks even when it should load them from storage, until the app is restarted.

**Comment by TacoCake** [comment]
Might be related to #156

**Comment by CappielloAntonio** [comment]
Hello, would you try this new version of the app?

[app-tempo-debug.zip](https://github.com/CappielloAntonio/tempo/files/14077736/app-tempo-debug.zip)

**Comment by CappielloAntonio** [comment]
By latest release, do you mean version 3.6.0 or version 3.7.0 (currently in pre-release)?

**Comment by curiousercreative** [comment]
@CappielloAntonio I had tried 3.6 but I just tried 3.7 and a quick test suggests the bug is resolved for me. Thanks!
