### ISSUE TITLE
[BUG] - When updating the downloaded songs no longer show up in the download section of the app

### ISSUE THREAD

**Issue by shadowjig** [CappielloAntonio/tempo#93]
I had v3.4.7 installed and had downloaded some songs to my phone.  I upgraded to v3.5.7 and the downloaded songs are now missing.  I have to redownload them.

## Expected behavior

I would expect downloaded songs to remain on my phone even when the app is updated.

## Environment
 - Android device: Pixel 7 Pro
 - Android OS version: 13
 - App version: 3.5.7
 - Other relevant details: N/A

**Comment by CappielloAntonio** [comment]
Hi @shadowjig, this shouldn't happen anymore. Due to a different download management I had to rewrite the part related to the db and the ui, which caused what you described in your issue.
